### ISSUE TITLE
Heightmap configuration

### ISSUE THREAD

**Issue by MockbaTheBorg** [Denvi/Candle#101]
Hi there,

I am running 1.1.6 and trying to mill a PCB. 
First though I would like to run a height map, but when I create one, the red area is already pre-defined, and the heightmap configuration below it is greyed out, so I cannot make any changes to the parameters or probe area size.
I have the latest GRBL as well.
Is there a step-by-step procedure of creating a heightmap I could follow?

Thanks a lot,
Marcelo.

**Comment by Denvi** [comment]
Hello, ensure "Keyboard control" is unchecked in "Jog" panel before working with heightmap.

**Comment by MockbaTheBorg** [comment]
Cool. That did it.

Thank you so much.

**Comment by MockbaTheBorg** [comment]
Works perfectly ... best GRBL player ever.
