### ISSUE TITLE
Backlash compensation

### ISSUE THREAD

**Issue by MockbaTheBorg** [Denvi/Candle#102]
Sorry to ask this question as an issue, as it is not really.

I have a .28mm measured backlash on my X axis. Is there any means of adding backlash compensation to Candle?
Maybe there is and I am missing it. If not it would be awesome to have it.
Thanks a lot. Candle is by far the best sender for GRBL. Awesome piece of code.

Cheers,
Marcelo.

**Comment by MockbaTheBorg** [comment]
Also ... I use Flatcam to make my PCBs, maybe the backlash could be fixed there?

**Comment by Denvi** [comment]
Hello, backlash should be compensated in the firmware.
[As I know, still in development.](https://github.com/grbl/grbl/wiki/Development-Path-and-Future-Needs)

**Comment by MockbaTheBorg** [comment]
You mean on GRBL firmware right?

**Comment by Denvi** [comment]
Yes

**Comment by MockbaTheBorg** [comment]
Cool ... I will keep an eye on it (and write a preprocessor in the meantime).

Thanks a lot ... closing the issue.
