### ISSUE TITLE
assemble the source code

### ISSUE THREAD

**Issue by felixa4** [Denvi/Candle#103]
Happy new year to all.
I would like to change and add something but can not assemble the sw: I tried with 5.4.2.mingw qt and qt 5.7.1 mingw; it assembles sw, generates a 40 MB file , then "the Candle prog stopped working ....".
help me please, bye

**Comment by jiarko** [comment]
have you tried the "release" build too? 

whne I encouter such kind of trouble I try making some breakpoints starting from the main constructor and run in debug, so I should be able to see at least where there is something "hanging":..
