### ISSUE TITLE
grbl 1.1 GUI not working properly

### ISSUE THREAD

**Issue by jiarko** [Denvi/Candle#105]
Hi,

I've tested the GRBL 1.1 and realized that:

1. tool position on path is not updated (seems the toll is waiting in its start position even if from table I read the command sent updating)

2. in the "State" group, the subgroup "machine coordinates" shows the FS into the "Z" textline but in this way it is not completely shown becuse too many characters to be shown

3. when in "idle" it is shown as "unknown"...

do I miss some settings to let the GUI understand it is a different GRBL version?

thanx
Andrea

**Comment by Denvi** [comment]
Hello, download Candle 1.1.x is for GRBL 1.1.

**Comment by Denvi** [comment]
It's right one & should work with GRBL 1.1.

**Comment by jiarko** [comment]
Sorry, I did wrong. The cande_1.1.7.zip has the"exe" file that works properly,

If I download the source code it is not updated yet... into the "candle.pro" file the VERSION is set equal to 1.0.11.. and once compiled does not work properly... can you make available the source code too?

thanx

**Comment by Denvi** [comment]
Checkout "grbl_1_1" branch.

**Comment by jiarko** [comment]
Thanx
