### ISSUE TITLE
Error WinXP SP3 "The procedure entry point strnlen could not be located in dynamic link library msvcrt.dll"

### ISSUE THREAD

**Issue by prulitarit** [Denvi/Candle#112]
When i run Candle 1.1 on Windows XP SP3 with vcredist_x86 2010 installed i got errors "The procedure entry point strnlen could not be located in dynamic link library msvcrt.dll". 

Please help me to run latest Candle on Windows XP.

**Comment by Denvi** [comment]
Install vcredist_x86 2013.

**Comment by prulitarit** [comment]
already installed vcredist_x86 2013. And no result! Still shows error "The procedure entry point strnlen could not be located in dynamic link library msvcrt.dll". 

What version of Qt did you used in windows xp x86 ?

**Comment by Denvi** [comment]
Qt 5.5.1

**Comment by Denvi** [comment]
Было здесь #99. 
Смотрите в сторону драйверов/поддержки OpenGL 2.0. Windows XP c ANGLE не работает.
Для простых задач можно включить программную отрисовку, для чего нужно удалить файл "d3dcompiler_47.dll"
