### ISSUE TITLE
Нужна помощь 

### ISSUE THREAD

**Issue by Kurmankozhoev** [Denvi/Candle#115]
Здравствуйте !
Мне нужен исходный код самой последней версии Candle 1.1.7   здесь скачал последнию версию исходного кода но оно отличается от версии Candle 1.1.7 например нет кнопки стоп ручного перемещения как здесь <img src="http://savepic.ru/12871891.png" border="0" alt="Изображение - savepic.ru — сервис хранения изображений" /> вообщем не могли бы вы выложить исходный код последней версии программы для Linux ?

**Comment by Kurmankozhoev** [comment]
У меня проблемы при компиляции подскажите в чем проблема <img src="http://savepic.ru/12906502.png" border="0" alt="Изображение - savepic.ru — сервис хранения изображений" /> <img src="http://savepic.ru/12878854.png" border="0" alt="Изображение - savepic.ru — сервис хранения изображений" />

**Comment by Denvi** [comment]
>например нет кнопки стоп 

Кнопка "стоп" есть только в ветке "grbl_1_1".

>проблемы при компиляции 

setPixelColor был заменен в одном из недавних коммитов, обновите рабочую копию исходного кода до последней версии.

**Comment by Kurmankozhoev** [comment]
@Denvi  Огромное вам спасибо, все получилось )
