### ISSUE TITLE
Open source 1.1.7

### ISSUE THREAD

**Issue by tuananhproed** [Denvi/Candle#134]
Hello Denvi 
I have upgraded grbl 1.1f and use open source of candle 1.1, but unfortunately it's not a new version and there are many bugs, i can only download bundled software, i use source code and Want to add a cool off switch, can you share the source code of Candle 1.1.7?
![capture](https://cloud.githubusercontent.com/assets/26741218/24405929/c248d0f0-13f0-11e7-87e3-676581cb83e1.PNG)

**Comment by Denvi** [comment]
Hi, latest code for GRBL 1.1 is in "grbl_1_1" branch. Check it out please.

**Comment by tuananhproed** [comment]
Hi, i got the grbl 1.1f version upgraded to my cnc, the candy 0.9 source code i rebuilt has not worked, the current candle 1.1 source code is not working well in jog mode, i It has been changed in Candle 1.1.7, please let me know how you did, I just want to make a few changes to interface 1.1.7 and add coolant toggle. I'm not a professional programmer. Sorry my english is not good
![1](https://cloud.githubusercontent.com/assets/26741218/24417316/2b0e69e4-1412-11e7-95dc-2dbc2eb24e43.PNG)
![1 7](https://cloud.githubusercontent.com/assets/26741218/24417320/2e21af60-1412-11e7-9cc8-ba033508f3d6.PNG)
![c248d0f0-13f0-11e7-87e3-676581cb83e1](https://cloud.githubusercontent.com/assets/26741218/24417382/5fa8606a-1412-11e7-9fea-724a90c1deee.PNG)

**Comment by tuananhproed** [comment]
I am very happy to find, thank you
