### ISSUE TITLE
Problem with large file size

### ISSUE THREAD

**Issue by tuananhproed** [Denvi/Candle#143]
Hello Denvi
I have a problem with large files, when starting to load into the program file an error message occurs, can you help me know the cause or how to fix it. Thank you.
![1](https://cloud.githubusercontent.com/assets/26741218/25736534/9cb56ece-319c-11e7-9d17-93e51844f4bc.PNG)

**Comment by Denvi** [comment]
Hi, how many lines your file has?
"Candle" doesn't optimized for low memory usage, it's consumes about 2,5 Gb with 5 million lines g-code file.

**Comment by tuananhproed** [comment]
Thank you Denvi for the positive, initially my nc file size was about 75Mb, I thought it did not fit and split the program into 5 steps, now I have 5 files, each file is small More than 20Mb and it works well.
However, there is one inadequacy that the Candle program does not automatically run the files one by one, I think you go up there menu to run programs in turn for the next update, Thank you.
