### ISSUE TITLE
В окне 3D просмотра отображаются не все движения станка

### ISSUE THREAD

**Issue by Elektron2016** [Denvi/Candle#161]
Видимо последние несколько движений станка обрезаются. Например в такой программе:
G21
G90
G94
F50.00
M03
G4 P1
G01 Z-2.5000
G01 X-13.5
G01 Y-41.5
G01 X0
G01 Y0
G00 Z5.0000
M05
Последние три движения не отображаются.

**Comment by Denvi** [comment]
У меня отображается

![image](https://user-images.githubusercontent.com/5119037/29688702-0d23f1ae-893a-11e7-9cc2-810d45581d22.png)

**Comment by Elektron2016** [comment]
А должно быть так [http://rgho.st/6JnL2L82q](url)

**Comment by Denvi** [comment]
Не работает ссылка

**Comment by Elektron2016** [comment]
Уже исправил.

**Comment by Denvi** [comment]
Разбирайтесь, можно drag&drop'ом вставить картинку.

**Comment by Elektron2016** [comment]
![1](https://user-images.githubusercontent.com/17587027/29689503-1b21d34c-892c-11e7-919f-6b9dc069617a.png)

**Comment by Denvi** [comment]
Теперь вижу.
На самом деле обрезаются начальные движения, вплоть до первой полностью определенной точки, а это:

~~~
G01 Y-41.5
~~~

**Comment by Elektron2016** [comment]
Как тогда должна выглядеть программа чобы всё отображалось корректно?

**Comment by Denvi** [comment]
Добавьте в начало

~~~
G4 P1
G0 X0 Y0 Z0
...
~~~

**Comment by Elektron2016** [comment]
Спасибо, не знал таких тонкостей.
