### ISSUE TITLE
Released version is not matching the mater version

### ISSUE THREAD

**Issue by clark-mu** [Denvi/Candle#162]
Dear Denvi

Thank you very much for your job. 

I downloaded your latest released version, which is 1.1.7. However, your src code in GitHub is still in version 1.0.12.

May you please check if the versions are correct synced?

Thank you

Clark

**Comment by Nandox7** [comment]
Noticed the same.
Was making it for OSX and the layout does not match 1.1.7 version.
http://i1097.photobucket.com/albums/g359/nandox7/Screen%20Shot%202018-01-04%20at%2012.50.46%20AM_zpsji2rsxit.png~original

**Comment by clark-mu** [comment]
Thanks. That helps!
