### ISSUE TITLE
Проблема с визуализатором (?) 

### ISSUE THREAD

**Issue by inFamousMcGrath** [Denvi/Candle#164]
Я управляю станком с помощью Arduino Mega 2560, с прошивкой 1.1f с репозитория grbl-Mega. Когда я запускаю на выполнение код, первое время всё идет хорошо - визуализатор показывает всё как надо, работает панель изменения подачи, скорости и оборотов и т.д. Но через некоторое время происходит что то странное - программа продолжает отправлять код, но визуализатор не двигается, меню не работают, координаты в верхнем правом углу замирают. но станок работает, и самое интересное, что вполне корректно, строки продолжают отправляться программой (работает автопрокрутка и статус строки кода), никаких ошибок, никаких уведомлений нет. Программа полностью отправляет станку файл, а потом замирает в таком положении, поэтому нужно перезапускать программу, чтобы нормально работать.
Снял видео - https://youtu.be/d9_p-221BcE

**Comment by Peter6891** [comment]
у меня подобная ситуация. только мк ATMega328. прошивка grbl 0.9j или 1.1f
периодически мигает красным статус ("Неизвестно)", а иногда просто статус горит зелёным ("Готов")
но через короткое время замирает программа, и чуть позже и контроллер замирает
...

**Comment by inFamousMcGrath** [comment]
Я определил проблему, поскольку пишу свою собственную программу (больше похожую на промышленную стойку). Всё дело в ошибках передачи. Эта программа никак не реагирует на ошибки протокола USB, которые есть на Atmega16, который стоит как UART преобразователь на Mega2560. Поэтому сначала пропадает визуализация, а позже и перестает работать сама отправка файлов.

**Comment by Peter6891** [comment]
у меня преобразователь не на меге, а на CH340G

**Comment by Peter6891** [comment]
подбор кварца с дробной частотой может решить проблему?
по рекомендации стоят на 12 и 16 МГц. может есть смысл подобрать с дробной частотой чтоб уменьшить потери данных передачи из-за не стыковок частот?

**Comment by Peter6891** [comment]
![default](https://user-images.githubusercontent.com/23585234/30027256-cf8b3274-9188-11e7-8247-2b73b13913f0.jpg)

**Comment by inFamousMcGrath** [comment]
Перекомпилируйте Grbl с baudrate 9600, пишут что помогает от потерь на CH340G

**Comment by Peter6891** [comment]
я вас немного опередил)) перекомпилировал именно на 9600 и 2 часа без перебоя отработал

**Comment by Peter6891** [comment]
спасибо.

**Comment by zdanat** [comment]
Уважаемый Peter6891, можете ли Вы поделиться перекомпиляции версией, я к сожалению не владею навыками подобных действий, а у меня возникла такая же проблема со станком. Спасибо.

**Comment by Peter6891** [comment]
а какие параметры именно вам нужны? у вас ATMega 328 ?
версия grbl какая?

**Comment by zdanat** [comment]
Grbl 0.9j и ATMega 328, все симптомы проблем как описаны в первом посту

**Comment by Peter6891** [comment]
[grbl.zip](https://github.com/Denvi/Candle/files/2205295/grbl.zip)
попробуйте

**Comment by zdanat** [comment]
Большое благодарю, буду пробовать

**Comment by Peter6891** [comment]
попробуйте так:

[grbl.zip](https://github.com/Denvi/Candle/files/2205305/grbl.zip)

**Comment by Peter6891** [comment]
в предыдущем (которое удалил) я забыл добавить файлы прошивки. в этом добавил.
