### ISSUE TITLE
Soft Start for M3

### ISSUE THREAD

**Issue by yamimann** [Denvi/Candle#172]
Hello,
i use a 2417 CNC with a new spindle motor. It would be fine if i can use a soft start (by software) for this motor because the start power consumption is very high and my PSU stopped. If i start the motor with 75% everything is fine but i have to speed up the motor manually. Is it possible to implement a routine to start the motor e.g. at 15% and then increasing to 100% in 2-3 seconds?

regards
Joerg

**Comment by Denvi** [comment]
GRBL firmware relative problem.

**Comment by pedjas** [comment]
SaintSmart released new stronger spindle motor for their CNC 3018 machine. Lots of people are reporting issues using it. It takes too much power to start that causes various issues. If started low speed and gradually speed up, it works fine.

Having option for soft start would resolve most of their problems.
