### ISSUE TITLE
What command does "Set Step Mode" send to GRBL?

### ISSUE THREAD

**Issue by selotipkusut** [Denvi/Candle#176]
For my thesis I'm trying to interface with GRBL without any 3rd party software, but my G-Code can only be sent using GRBL's streaming script AFTER I use the "set step mode" function in Candle.

This is the streaming script that I use:
[https://github.com/grbl/grbl/blob/master/doc/script/simple_stream.py](url)

**Comment by Denvi** [comment]
Hello, what is "set step mode" function in Candle?

**Comment by selotipkusut** [comment]
I found out that this function was a modification added by a student that used the machine last year, sorry for the trouble.
