### ISSUE TITLE
совместимость версий.

### ISSUE THREAD

**Issue by bvaleri** [Denvi/Candle#193]
Вместе с купленным CNC2418 прислали диск с GRBLControl 0.8. Всё работает. Попробовал версию 0.84 -- не работает функция возврата в нулевые координаты. Попробовал Candle -- Вообще не передаётся программа, ругается на команду "T1 M06", говорит, что не понимает её. Это у меня руки кривые и что-то нужно настраивать или действительно с моим станком и его прошивкой более новые версии не будут работать?

**Comment by Denvi** [comment]
Понаприсылают дисков...

> не работает функция возврата в нулевые координаты.

Поясните подробнее, как не работает?

> ругается на команду "T1 M06"

Ругается то прошивка, которая не поддерживает команду "M06".

> действительно с моим станком и его прошивкой более новые версии не будут работать?

Для версий "Candle 1.1.x" нужна прошивка GRBL 1.1.
