### ISSUE TITLE
Feed Control Over Ride for candle 1.10.70

### ISSUE THREAD

**Issue by Kim9999** [Denvi/Candle#217]
Denvi
Is there a way to slow the feed below 10%  I need a slow feed rate.  
Thank you

**Comment by ASHIT-AXAR** [comment]
simply open your gcode file in a text editing program and change the Feedrate manually.
ex: Notpad++ (using replace all command)

**Comment by Kim9999** [comment]
Thank you found it.  Needed to lower $ 120,121,122 settings.   Worked like a charm Thanks
