### ISSUE TITLE
Error building heightmap

### ISSUE THREAD

**Issue by deepfryed** [Denvi/Candle#219]
z-probe and homing is working, I am wondering if this is a hardware issue but looks like grbl doesn't like the gcode. I get an error immediately after I start building the heightmap.

![](https://i.imgur.com/2ezCHKV.png)

Any advice would be appreciated
Thanks

**Comment by deepfryed** [comment]
I had the Zt and Zb setup incorrectly :man_facepalming:

**Comment by nickm324** [comment]
It would be beneficial to others if you find a resolution to post it here, even if you did open the issue.
