### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by houguang** [Denvi/Candle#228]
![image](https://user-images.githubusercontent.com/1720347/38685121-c0f98c9c-3ea3-11e8-8815-0b5189911b62.png)
![image](https://user-images.githubusercontent.com/1720347/38685146-cfb1943c-3ea3-11e8-9c00-b47e73072cc7.png)
![image](https://user-images.githubusercontent.com/1720347/38685207-ea0cfede-3ea3-11e8-95c9-6f1dca0adf42.png)
Error opening 50M file

**Comment by houguang** [comment]
this is attachment 
[1.zip](https://github.com/Denvi/Candle/files/1903679/1.zip)

**Comment by ASHIT-AXAR** [comment]
how much is your computer RAM size ?
you can split your file into smaller parts

**Comment by houguang** [comment]
> how much is your computer RAM size ?
> you can split your file into smaller parts

8G

**Comment by houguang** [comment]
this question no anwser?
