### ISSUE TITLE
No communication on Debian 9 with Grbl-1.1g

### ISSUE THREAD

**Issue by richardklingler** [Denvi/Candle#237]
Launching Candle and select the serial port fo the Grbl controller shows after a while the status as "unknown" and no communication takes place.

Machine coordinates are displayed as: 0.000 0.000 0.000|FS:0

However in the Grbl console I can send commands and get a response.

**Comment by Denvi** [comment]
Hi, look like wrong Candle version.
For the GRBL-1.1 firmware there is Candle 1.1.7 in releases.

**Comment by richardklingler** [comment]
That's the version which doesn't display any menu....so even more unusable on Debian 9 ;-)
So had to use compile the git version...

**Comment by richardklingler** [comment]
Checked out the grbl_1_1 branch and this seems to work...

**Comment by richardklingler** [comment]
Consider this closed ;-)
