### ISSUE TITLE
Settings not stored after a restart on Debian 9

### ISSUE THREAD

**Issue by richardklingler** [Denvi/Candle#238]
No settings are saved on Debian, like serial port, baudrate, whatever...

**Comment by Denvi** [comment]
May be access rights issues, "settings.ini" is in binary folder.

**Comment by richardklingler** [comment]
Hmm..it doesn't like to be copied over to like /usr/local/bin....so have it now in my home directory....then the settings are saved ;-)

**Comment by Perlovka** [comment]
Why not to use standard system config locations?

Here is the patch:
[fix-config-location.patch.txt](https://github.com/Denvi/Candle/files/4306528/fix-config-location.patch.txt)
