### ISSUE TITLE
Mac version ?

### ISSUE THREAD

**Issue by Xav83130** [Denvi/Candle#32]
Good evening,
it would be possible to compile a version for "Mac"?
If it's not too complicated.
Thank you

**Comment by Denvi** [comment]
I think it's possible.
But I haven't Mac, sorry.

**Comment by Xav83130** [comment]
you think I could try to do? knowing that I have no knowledge on the subject?

**Comment by Denvi** [comment]
Why not?
1) Download Qt for OS X from here: http://download.qt.io/official_releases/qt/5.5/5.5.1/qt-opensource-mac-x64-clang-5.5.1.dmg.mirrorlist
2) Install Qt.
3) Download source code of grblControl.
4) Start Qt Creator and open "grbl_control.pro" project file from "src" directory of sources.
5) Build grblControl (look for image bellow).
6) Post any compiling errors here.

![qt_build_1](https://cloud.githubusercontent.com/assets/5119037/12855620/4c52b446-cc62-11e5-8aa5-3239fad92c39.png)

**Comment by Xav83130** [comment]
1 test and 1 error messages
![1st test](http://pix.slic.it/p/6c3)

**Comment by Denvi** [comment]
Try to replace "std::isnan" with "qIsNan" in whole project.

**Comment by Xav83130** [comment]
after changes

![1st test](http://pix.slic.it/p/6c7)

**Comment by Denvi** [comment]
#include <math.h> to top of interpolation.h

**Comment by Xav83130** [comment]
result
![1st test](http://pix.slic.it/p/6c8)

**Comment by Denvi** [comment]
If replace \<math.h\> with \<cmath\> ?

**Comment by Xav83130** [comment]
![1st test](http://pix.slic.it/p/6c9)

**Comment by Denvi** [comment]
Sure using \<cmath\>? not \<cmath.h\>.

**Comment by Xav83130** [comment]
it's better with <cmath>
![1st test](http://pix.slic.it/p/6ca)

**Comment by Denvi** [comment]
Remove
>>> 
#include "math.h"

from "gcodedrawer.cpp" source file. Or replace with #include \<cmath\> if failed to compile.

**Comment by Xav83130** [comment]
same result with two
![1st test](http://pix.slic.it/p/6cb)

**Comment by Denvi** [comment]
Think need to repeat previous steps for these files:
tooldrawer.cpp
gcodeparser.cpp
gcodepreprocessorutils.cpp

In "heightmapgriddrawer.cpp" line 32 looks the same as:
~~~
if (m_model == NULL || qIsNaN(m_model->data(m_model->index(i, j), Qt::UserRole).toDouble())) {
~~~
?

**Comment by Xav83130** [comment]
for "heightmapgriddrawer.cpp" line 50 and 64 also ?

**Comment by Denvi** [comment]
Use advanced search:
![search1](https://cloud.githubusercontent.com/assets/5119037/12866998/4423ac3e-cd03-11e5-8b51-a87497f9921f.png)

Select "Current project", string to find "std::isnan", check "Case sensitive" and press "Find and replace" button:
![search2](https://cloud.githubusercontent.com/assets/5119037/12867005/7e3a96d0-cd03-11e5-97e0-9841e80c81d8.png)

Enter "Replace to": "qIsNaN" and press "Replace" button:
![search3](https://cloud.githubusercontent.com/assets/5119037/12867013/bcf9aad2-cd03-11e5-9cb4-af7f1d63b916.png)

**Comment by Xav83130** [comment]
![1st test](http://pix.slic.it/p/6cc)

**Comment by Denvi** [comment]
It's easy, just repeat previous step to replace "NAN" with "qQNaN()"

**Comment by Xav83130** [comment]
successful compilation

**Comment by Denvi** [comment]
How about pressing big green arrow?

**Comment by Xav83130** [comment]
the program starts without problems !!!!!
I just connect the milling machine,
it connects.
little problem:
in preferences: colors are all black.
but I can change them manually

**Comment by Denvi** [comment]
Need to apply "Default settings" after first start to get normal colors.

**Comment by Xav83130** [comment]
it is good with to apply "Default settings".
Now i go test command machine manually.

**Comment by Xav83130** [comment]
THE MACHINE MOOOOOOVE is too good

**Comment by Xav83130** [comment]
what should he do now?
to install on the Mac.

**Comment by Denvi** [comment]
You should use "macdeployqt" util from "QTDIR/bin/" folder to get .dmg file.

Open terminal, change directory to grbl_control build folder with "cd" command (it should be above sources like this one: "build-grbl_control-Desktop_Qt_5_4_2_MinGW_32bit-Release")

~~~
cd path_to_grbl_control.app
~~~

Then:
~~~
$QTDIR/bin/macdeployqt grbl_control.app -dmg
~~~

I beleive it will create .dmg file in build directory.

**Comment by Xav83130** [comment]
it is complicated for me ....
I look at all this in one hour

**Comment by Xav83130** [comment]
Ok i understand for create a .dmg
but when i run .dmg i have error

"Dyld Error Message:
  Library not loaded: @rpath/QtOpenGL.framework/Versions/5/QtOpenGL
  Referenced from: /Applications/grbl_control.app/Contents/MacOS/grbl_control
  Reason: image not found"

**Comment by Denvi** [comment]
May be change "grbl_control.pro" file:
~~~
unix: {
    DEFINES += UNIX #GL_GLEXT_PROTOTYPES
    QMAKE_LFLAGS += "-Wl,-rpath,\'\$$ORIGIN/libs\'"
}
~~~
to 
~~~
unix:!macx {
    DEFINES += UNIX #GL_GLEXT_PROTOTYPES
    QMAKE_LFLAGS += "-Wl,-rpath,\'\$$ORIGIN/libs\'"
}
~~~
will help.

How about just run "grbl_control.app"? Or rebuild, run "macdeployqt" without "-dmg" flag and start "grbl_control.app".

**Comment by Xav83130** [comment]
grbl_control.app works.
I still tried to do the .dmg but without success.

Thank you anyway.

**Comment by Xav83130** [comment]
When I disconnect the USB computer "grbl control" crash.

**Comment by Denvi** [comment]
Fixed in one of the latest commits.
