### ISSUE TITLE
cnc3018 . when i sent gcode to machine it be come smaller than the real size to smaler 

### ISSUE THREAD

**Issue by mbalakash** [Denvi/Candle#331]
cnc3018 . when i sent g code to machine it be come smaller than the real size i used easel to making the project i think i tried many things it same issue 

cnc card is cronosmaker 
windos 10
candle 32

**Comment by mbalakash** [comment]
version 1.1.7

**Comment by ASHIT-AXAR** [comment]
Reasons are:
- Machine Units and Job Units are not the same (Metric or Imperial).
- Drivers are not calibrated.

**Comment by mbalakash** [comment]
How i do it

**Comment by ondras12345** [comment]
Open your gcode and try to find one of these commands: [`G20`, `G21`](http://linuxcnc.org/docs/html/gcode/g-code.html#gcode:g20-g21).

There is also a GRBL setting [`$13`](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#13---report-inches-boolean) that sets the units your machine reports back.

And there's also a setting in Candle 'Machine information: Units' that should match the `$13` setting.

**Comment by mbalakash** [comment]
Thank you so much I'll try it to day

**Comment by mbalakash** [comment]
The probe commands is :G21G91G38. 2Z-30F100;G0Z1;G38.27-2F10
and the safe position commands is : G21G90;G53G0Z0
and i sent the $13 
but still same problem

**Comment by pedjas** [comment]
Maybe machine is not calibrated.

Set head to edge to be close to machine construction. Find point where you may easily measure distance form head to construction.

Then send command to move head for specific distance (10 cm, 20 cm..). Measure distance of the head from the same spot on construction and see what actual distance head traveled. If it does not match to the command it is not calibrated.

**Comment by ondras12345** [comment]
> The probe commands is :G21G91G38. 2Z-30F100;G0Z1;G38.27-2F10
> and the safe position commands is : G21G90;G53G0Z0

I wanted you to find the G21 command **in the g-code program file** you are running, so that we can determine whether your job is in inches or mm.

I also wanted you to check the `Machine information: Units` setting in Candle. Probe commands and safe position commands are not involved in this problem.

> and i sent the $13

I'm not sure what this sentence means. Did you issue the `$$` command to see the settings?

**Comment by ondras12345** [comment]
> Then send command to move head for specific distance (10 cm, 20 cm..). Measure distance of the head from the same spot on construction and see what actual distance head traveled. If it does not match to the command it is not calibrated.


Reset the machine and type `G91 G0 X1 G90` to the console. This should move +1 (mm or ") relative to current position on the X axis.

Measure the distance it traveled. If it is 1mm, then your machine units are mm. If it is 25.4mm, your machine units are inches.

If it is something else, you may have a calibration problem. Post your `$$` settings in this case.

**Comment by mbalakash** [comment]
> > Then send command to move head for specific distance (10 cm, 20 cm..). Measure distance of the head from the same spot on construction and see what actual distance head traveled. If it does not match to the command it is not calibrated.
> 
> Reset the machine and type `G91 G0 X1 G90` to the console. This should move +1 (mm or ") relative to current position on the X axis.
> 
> Measure the distance it traveled. If it is 1mm, then your machine units are mm. If it is 25.4mm, your machine units are inches.
> 
> If it is something else, you may have a calibration problem. Post your `$$` settings in this case.

I sent it in console and >error:21

**Comment by mbalakash** [comment]
> > The probe commands is :G21G91G38. 2Z-30F100;G0Z1;G38.27-2F10
> > and the safe position commands is : G21G90;G53G0Z0
> 
> I wanted you to find the G21 command **in the g-code program file** you are running, so that we can determine whether your job is in inches or mm.
> 
> I also wanted you to check the `Machine information: Units` setting in Candle. Probe commands and safe position commands are not involved in this problem.
> 
> > and i sent the $13
> 
> I'm not sure what this sentence means. Did you issue the `$$` command to see the settings?

![15794565787957953257799600681724](https://user-images.githubusercontent.com/59981534/72685745-2bd98000-3afe-11ea-801e-e218f3285f0e.jpg)
Did you mean that

**Comment by ondras12345** [comment]
> error:21

Ok, GRBL needs the commands separately:
```
G91
G0 X1
G90
```

**Comment by ondras12345** [comment]
> > > The probe commands is :G21G91G38. 2Z-30F100;G0Z1;G38.27-2F10
> > > and the safe position commands is : G21G90;G53G0Z0
> > 
> > 
> > I wanted you to find the G21 command **in the g-code program file** you are running, so that we can determine whether your job is in inches or mm.
> > I also wanted you to check the `Machine information: Units` setting in Candle. Probe commands and safe position commands are not involved in this problem.
> > > and i sent the $13
> > 
> > 
> > I'm not sure what this sentence means. Did you issue the `$$` command to see the settings?
> 
> ![15794565787957953257799600681724](https://user-images.githubusercontent.com/59981534/72685745-2bd98000-3afe-11ea-801e-e218f3285f0e.jpg)
> Did you mean that

Yes, your Job units are mm then. What factor do the dimensions get reduced by when you actually run the job? (The result should be the same as with the test commands I sent in my previous post.)

**Comment by mbalakash** [comment]
![15794574070667840032195270806722](https://user-images.githubusercontent.com/59981534/72685943-1cf3cd00-3b00-11ea-9eb4-75546d731676.jpg)
That to opjects by same gcod and (mm)

**Comment by ondras12345** [comment]
This is most likely a calibration problem. Try to determine the reduction factor and post your `$$` settings.

**Comment by mbalakash** [comment]
> This is most likely a calibration problem. Try to determine the reduction factor and post your `$$` settings.

**Comment by mbalakash** [comment]
![15794580283063012737256466486232](https://user-images.githubusercontent.com/59981534/72686063-8d4f1e00-3b01-11ea-80a4-74d6616f1278.jpg)
..

**Comment by mbalakash** [comment]
![15794580600248088496297037809514](https://user-images.githubusercontent.com/59981534/72686073-a061ee00-3b01-11ea-8221-a402609e36f0.jpg)
2

**Comment by mbalakash** [comment]
![15794580952138461270049087751587](https://user-images.githubusercontent.com/59981534/72686080-b7a0db80-3b01-11ea-82ed-564ca8270c8b.jpg)
3

**Comment by mbalakash** [comment]
![15794581252788047165310552872596](https://user-images.githubusercontent.com/59981534/72686089-c7b8bb00-3b01-11ea-89a2-bd0c651c7747.jpg)
4

**Comment by mbalakash** [comment]
![15794581529765558437115481130003](https://user-images.githubusercontent.com/59981534/72686094-d56e4080-3b01-11ea-834d-772fa4a0b427.jpg)
End

**Comment by mbalakash** [comment]
> This is most likely a calibration problem. Try to determine the reduction factor and post your `$$` settings.

Isent pictures of $$ settings can you till if any thing goes wrong

**Comment by ondras12345** [comment]
The problem _may_ be the `$100`-`$102` settings. The [first google search result](https://forum.arduino.cc/index.php?topic=627389.0) says it should be 800.

**Comment by mbalakash** [comment]
Ill try it

**Comment by mbalakash** [comment]
It gose worse  

> The problem _may_ be the `$100`-`$102` settings. The [first google search result](https://forum.arduino.cc/index.php?topic=627389.0) says it should be 800.

**Comment by mbalakash** [comment]
Whin I clicked at send it terns of and it fixed the size issue

**Comment by mbalakash** [comment]
I am trying to send video for it

**Comment by mbalakash** [comment]
It fixed thanks everyone
I used $3=5
