### ISSUE TITLE
( candle stopped working )

### ISSUE THREAD

**Issue by samehherit** [Denvi/Candle#348]
Hi every body ,,
Im using candle controller v. 1.2b on my mini cnc
When im trying to open the app this message appears in windows /
( candle stopped working )
I need to fix this problem please

**Comment by ondras12345** [comment]
Hi,
v1.2b is an experimental version. Try using a stable [release](https://github.com/Denvi/Candle/releases).

**Comment by samehherit** [comment]
Thanx alot
