### ISSUE TITLE
CNC3018 engraving in reverse.

### ISSUE THREAD

**Issue by RLBeadon** [Denvi/Candle#353]
Good Day

I have been trying to engrave my name into a piece of wood.

The art work is done and the gcode generated in Easel.

The preview shows the engraving the right way around.

I then open it in grblControl and send for engraving after completing the necessary set up.

When the engraving begins the writing is written backwards. 

How do I resolve this?

Many thanks

Rodney

**Comment by ondras12345** [comment]
Hi,
take a look at the [$3 GRBL setting](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#3--direction-port-invert-mask).
