### ISSUE TITLE
Add an Issue Template

### ISSUE THREAD

**Issue by ondras12345** [Denvi/Candle#359]
Hi @Denvi 
I've been thinking about adding an [issue template](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) to this repository. Maybe something like this:

[Candle-issue-template.txt](https://github.com/Denvi/Candle/files/4457078/Candle-issue-template.txt)

Could you add it, please? I think it should reduce the number of new issues opened by people who just got their new machine and haven't read the Grbl docs at all, and thus make it simpler for you (and potentially other people) to focus on the development of this great piece of software.

Thanks.

Edit: I added a link to Candle wiki. New file: 
[Candle-issue-template.txt](https://github.com/Denvi/Candle/files/4461055/Candle-issue-template.txt)

**Comment by Denvi** [comment]
Thank you, good idea. Will add some templates.
