### ISSUE TITLE
Text rendered as black squares

### ISSUE THREAD

**Issue by oomek** [Denvi/Candle#409]
**Versions**
 - Candle version: 1.2.9b
 - Firmware version: 1.1h

**PC info**
- OS: Windows 10 Home
- OpenGL version: 4.6.13596

**Describe the bug**
The latest version renders text as black squares, previous version renders text normally

**Screenshots**
![image](https://user-images.githubusercontent.com/2974860/90134532-393fab80-dd69-11ea-933d-881313995de2.png)

**Comment by Jose-Manuel34** [comment]
Hi, did you solve your problem. I have a similar situation and I haven't found a way to solve it.

![Candle](https://user-images.githubusercontent.com/55162981/102655823-8f1dc900-4138-11eb-8d81-f7e551ed5636.PNG)

**Comment by oomek** [comment]
The issue resolved by itself a while back, but honestly I have no idea how. Maybe by the gpu driver update, who knows.
