### ISSUE TITLE
Candle v1.2.9.2b special crash!!!

### ISSUE THREAD

**Issue by vladi552** [Denvi/Candle#438]
How to recreate:
1. Load CNC file included.
2. Start the job.
3. It freezes at line 3.
4. Pay attention to line 3 nature. If the UPPER case down to lower case and last caracter in UPPER case is digit, the Candle cannot handle this and next command transmission is failed.
[TC80M2display.GTL_iso_cnc.zip](https://github.com/Denvi/Candle/files/5358867/TC80M2display.GTL_iso_cnc.zip)

**Comment by Denvi** [comment]
Thank you. Problem is 'M2' in the line.

**Comment by Denvi** [comment]
Solved in 1.2.11b.
