### ISSUE TITLE
Why is Candle moving the decimal point from my g-code file?

### ISSUE THREAD

**Issue by gbach55** [Denvi/Candle#445]
**Versions**
 - Candle version: 1.1.7
 - Firmware version: unsure for now... new machine

**PC info**
- OS: Win7
- OpenGL version: unsure

**Describe the bug**
I create a command to move an inch and it gets read as what seems to be .001

**To Reproduce**

**Expected behavior**
I expect to have it move the distance I have set... not a microscopic copy of it.

**Screenshots**
If applicable, add scree
[eighth inch end mill.tap.txt](https://github.com/Denvi/Candle/files/5541597/eighth.inch.end.mill.tap.txt)

nshots to help explain your problem.

**Example files**
G0X-10.3146Y49.6063Z0.9843               This thing will only move a millimeter or so...

**Additional context**
If I create a model at 10 times the dimensions... ie 30" as opposed to 3"    then I can get it to move about halfway to where it needs to go.

**Comment by gbach55** [comment]
My copy of Candle is moving my SainSmart 4030 .001" for a command to move 1".   How do I fix this?   I can't find anything within settings to get it back to full scale.

**Comment by ondras12345** [comment]
Please fill in the issue template in your first post. We need more info about this, particularly the an example of the G-code command you are having problems with.

**Comment by Denvi** [comment]
Try to add G20 command to the program beginning.

**Comment by gbach55** [comment]
Not sure yet that the G20 code helped... but I did find that after I repositioned the stock it worked.  It seems I had it placed outside the machine limits.  Anyway... things are working as expected now.   I am going to have fun with this machine!
