### ISSUE TITLE
Where is the button search for z

### ISSUE THREAD

**Issue by Nezarod** [Denvi/Candle#463]
- Candle version: 1.2.12b

In version 1.2.9 this button was.
Disappeared in the new version.
I tried creating a button and pasting the search code h from version 1.2.9.
G92X.00Y.00Z.00; G21G91G38.2Z-30F100; G0Z1; G38.2Z-2F10; G92Z.00; G0Z1
But nothing worked for me ((
Please tell me how to return this function?

**Comment by Denvi** [comment]
Split code into multiple lines by semicolons and remove semicolons.

**Comment by Nezarod** [comment]
Thank!
Happened.
I thought that you can insert as in the old version.
