### ISSUE TITLE
"Run from here" or equivalent

### ISSUE THREAD

**Issue by mdatt** [Denvi/Candle#464]
Hello, it's possible to resume a job that was interrupted by PC Windows StandBy?
I'd like to restart the job by the first line of gcode that is in the queue state (the previous line is in processed state)
Thank you very much

**Comment by Braunfeltd** [comment]
yes, turn off standby on g.code sender machine.   It can cause all sorts of bad :)

**Comment by mdatt** [comment]
I tied but the result was an through hole. Into candle 1.1.7 Inselected the last line processed and I push the Send button, no pup up was opened and the drill turn on and perform an hole...Where is my error?
