### ISSUE TITLE
Cutter compensation 

### ISSUE THREAD

**Issue by Carltonbeach** [Denvi/Candle#470]
Does candle have a cutter comp feature? I would like to have the ability to comp to bring in the feature to.the correct size. Is this done by changing the tool diameter rather than using a offset?

**Comment by pedjas** [comment]
Candle just executes g-code. Compensation for tool size should be already in g-code.

**Comment by CNCaddicted** [comment]
Carbide Create does a nice job of cutter comp. You can select outside, inside, or none

**Comment by Carltonbeach** [comment]
is this another open source software?
    On Wednesday, April 21, 2021, 08:20:40 AM EDT, CNCaddicted ***@***.***> wrote:  
 
 


Carbide Create does a nice job of cutter comp. You can select outside, inside, or none

**Comment by CNCaddicted** [comment]
It is not open source but it is free software that Carbide3D supplies for
download for use with their Shapeoko machines, but it generates Gcode for a
variety of platforms, such as general grbl..
