### ISSUE TITLE
How to get src for Candle 1.0 ?

### ISSUE THREAD

**Issue by J-Dunn** [Denvi/Candle#484]
_(for GRBL v0.9 and below use Candle 1.0)_

You have a drop down list of branches but I don't see Candle 1.0 , how can I get the source for the right version for use with GRBL 0.9x ? 

More explicit instructions or inclusion in the drop down list would be very useful.

Many thanks.

**Comment by ondras12345** [comment]
There is a tag for that.
See https://github.com/Denvi/Candle/releases
https://github.com/Denvi/Candle/releases/tag/v1.0
https://github.com/Denvi/Candle/tree/v1.0

**Comment by J-Dunn** [comment]
many thanks, I'll check it out. :)
