### ISSUE TITLE
3mm delta between reset tool origin and reset origin

### ISSUE THREAD

**Issue by acw400** [Denvi/Candle#496]
**Versions**
 - Candle version: 1.1.7
 - Firmware version: not sure how to get it. Out of the box Saintsmart ProvenXL 4030

**PC info**
- OS: Windows 10
- OpenGL version: ...

**Describe the bug**

**To Reproduce**
- move the tool to a desired x,y coordinate
- press reset origin to define tool origin
- press restore origin
-the tool moves +3mm on both x and y axis.

**Expected behavior**
nothing moves

Note: I checked the box in settings to enable restore origin on a plane. In spaces option does the same thing.

**Screenshots**

**Example files**
Add G-code files that cause problems.

**Additional context**

**Comment by Denvi** [comment]
Hi, please '$#' command output.

**Comment by acw400** [comment]
$# < [G54:-3.000,-3.000,-3.000]
[G55:0.000,0.000,0.000]
[G56:0.000,0.000,0.000]
[G57:0.000,0.000,0.000]
[G58:0.000,0.000,0.000]
[G59:0.000,0.000,0.000]
[G28:0.000,0.000,0.000]
[G30:0.000,0.000,0.000]
[G92:0.000,0.000,0.000]
[TLO:0.000]
[PRB:0.000,0.000,0.000:0]
ok


Looks like G54 is the offset causing problems. I'm new to gcode. Not sure why this is set..

**Comment by ondras12345** [comment]
These offsets are stored in the EEPROM. Once you set them, they'll survive resets of the Grbl firmware.
Try [`G10 L2 P1 X0 Y0 Z0`](http://linuxcnc.org/docs/html/gcode/g-code.html#gcode:g10-l2).

**Comment by acw400** [comment]
That fixed it. Thank you *so* much!
