### ISSUE TITLE
Candle Restore Origin KO ?

### ISSUE THREAD

**Issue by REVESETOILES** [Denvi/Candle#499]
When starting the machine CNC 3018 Prover SainSmart , I click on Home, the machine is positioned with the limit switches. I jog in X and Y. then I click on Zero XY. I jog again and click on restore the origin. But the machine doesn’t go back to zero, but it moves at all speeds in the opposite direction. It has never done that in the past.
Thank you for yours help

**Comment by ondras12345** [comment]
Hi, take a look at https://github.com/Denvi/Candle/issues/496

**Comment by REVESETOILES** [comment]
Thank You,

It's ok for me..
