### ISSUE TITLE
Strange Heightmap Values? 

### ISSUE THREAD

**Issue by jeremylaratro** [Denvi/Candle#506]
**Versions**
 - Candle version: 1.1.7
 - Firmware version: 1.1h

**PC info**
- OS: Windows 10
- OpenGL version: ...

**Describe the bug**
I'm getting very extreme heightmap values (between -7 - +5). There are huge drops at the end of the boards, where the real difference is within a millimeter. This is on copper clad pcb board, so its nothing overtly bendable or uneven. 

**To Reproduce**
I set the z probe, and zero the x,y, and z axes. Then I start the heightmap ( Create -> Auto -> probe). The probing works normally.

**Expected behavior**
Heightmap with accurate values

**Screenshots**
https://ibb.co/31rH2qB
https://ibb.co/yPfKCvr

**Comment by Denvi** [comment]
Is the steps/mm firmware settings correct?
Need "settings.ini" file from Candle folder & "$$" firmware command output.
