### ISSUE TITLE
Candle "jog" buttons deactivated at hold for changing to finishing cutting bit.  Cannot raise Spindle

### ISSUE THREAD

**Issue by Rroe34293** [Denvi/Candle#507]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Rroe34293** [comment]
Is there a way to activate the Candle Software buttons when my program reaching the halfway point and has paused to begin itself on a Finish cut?     I need to change cutting bits at this point and cannot raise the spindle because the Candle Jog buttons are not active.    Is there a way to activate these to allow raising the spindle for clearance to change out a cutting bit?

**Comment by itsMe2021** [comment]
Cannot get any version of Candle jog buttons to work! Used my usual laptop with GrblControl running…and a new laptop with only Win 10 included apps.
Again Candle 2.3 and 2.2…the jog buttons do not function.
Cannot be com issues, new laptop, tried 3 usb ports..buttons do not function!

**Comment by ondras12345** [comment]
> Candle 2.3 and 2.2

There is no such version. See https://github.com/Denvi/Candle/releases
This is probably because you are using Grbl firmware older than v1.1. [README](https://github.com/Denvi/Candle#downloads) says:
> (for GRBL v0.9 and below use Candle 1.0)

**Comment by Denvi** [comment]
#521
