### ISSUE TITLE
Console command input field inactive

### ISSUE THREAD

**Issue by modsley** [Denvi/Candle#517]
**Versions**
 - Candle version: 1.1.7
 - Firmware version: 1.1f

**Describe the bug**
Port opened, jog control is working.
Input field for console commands is grayed, so I can't send console commands.

**Additional context**
Add any other context about the problem here
![Screenshot 2021-10-05 180142](https://user-images.githubusercontent.com/37621523/136052184-c6b90ba3-5a9a-4ba2-8b0e-7913d2be358a.png)
.

**Comment by ondras12345** [comment]
Try pressing `Scroll Lock`. Maybe you are in keyboard control mode.

**Comment by modsley** [comment]
Yeah... When Keyboard control is checked console input is disabled. Thank you.
