### ISSUE TITLE
Can it be deployed to an android phone? I have an old android phone

### ISSUE THREAD

**Issue by hankecnc** [Denvi/Candle#518]
Can it be deployed to an android phone? I have an old android phone

**Comment by hankecnc** [comment]
I have connected to my mobile phone through the USB virtual serial port of my GRBL circuit board, and sent the G code to make the machine move. Can the candle run on Android? Isn't qt run on Android?

**Comment by hemangjoshi37a** [comment]
💬 Candle is Qt so it can't run on Android, but I built a browser successor — **karmyogi** (https://karmyogi.hjlabs.in) — that follows the same workflow and runs in Chrome on Android with no install, so an old phone becomes a GRBL controller. Disclosure: I'm the author.
