### ISSUE TITLE
Ошибка разметки рабочего поля

### ISSUE THREAD

**Issue by syph3r** [Denvi/Candle#519]
**Versions**
 - Candle version: 1.2.14b
 - Firmware version:  1.1h с 0,0 а левом нижнем углу и  позитивными рабочими координатами.

**PC info**
- OS: Windows 7
- OpenGL version: ...

**Describe the bug**
Ошибка в отрисовкие границ рабочего поля (серая рамка с размерностью вычитанной из настроек grbl станка). При уходе станка домой 0,0 (в физический левый нижний угол) - на 3Д рендере отображается фреза в верхнем правом углу прямоугольника границ рабочей зоны. Соответственно любая дальнейшая отрисовка управляющей программы выполняется за границами данного серого прямоугольника. В остальном плане сбоев из-за дома в левом нижнем углу и позитивных рабочих координат не выявлено. Возможно ли сделать рациональный выбор данной особенности в настройках, раз автоматически проблемно определить ?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Example files**
Add G-code files that cause problems.

**Additional context**

**Comment by syph3r** [comment]
![Uploading IMG_20211017_145414.jpg…]()

**Comment by syph3r** [comment]
![IMG_20211017_145414](https://user-images.githubusercontent.com/13466623/137626232-333424b1-9b9d-432d-88bd-62a8f65860ed.jpg)

**Comment by Denvi** [comment]
#527
