### ISSUE TITLE
Continuous manual mode does not work.

### ISSUE THREAD

**Issue by tistructor** [Denvi/Candle#527]
**Versions**
 - Candle version: 1.2.13b
 - Firmware version: 1.1f

**PC info**
- OS: Windows10
- OpenGL version: ...

**Describe the bug**
I added the microswitches to perform the zero machine and the hardware zeroing works but the manual axis movement mode works only in step mode and not in continuous, it returns error 15.

https://user-images.githubusercontent.com/24445373/146651267-12e2e2fa-0674-4f69-818d-50e9d89b3491.mp4

These are the parameters of the CNC3018Pro:

$1=25
$2=0
$3=6
$4=0
$5=0
$6=0
$10=2
$11=1.000
$12=0.002
$13=0
$20=1
$21=1
$22=1
$23=7
$24=25.000
$25=500.000
$26=25
$27=0.500
$30=1000
$31=0
$32=1
$100=800.000
$101=800.000
$102=800.000
$110=2000.000
$111=2000.000
$112=100.000
$120=20.000
$121=20.000
$122=20.000
$130=315.000
$131=172.000
$132=42.000
ok
 
This is the application screen:
<img width="960" alt="Cattura1" src="https://user-images.githubusercontent.com/24445373/146651446-89439c4d-471d-4223-bc18-e58de24ea9ff.PNG">

**Comment by tistructor** [comment]
Before this change it worked fine.
Will it be due to the value of the allowed ranges on the three axes ($130, $131, $132)?

**Comment by tistructor** [comment]
If I run this command it works: G21G91X10F2000
This command works G21G91X-0.005Y0.000Z0.000F2000 if they are not at machine zero but it moves by 5 thousandths of a millimeter.
Continuous mode commands seem wrong!

**Comment by Denvi** [comment]
Hello.
Please set $10=3 setting, as for $10=2 there is no coordinates update from firmware.
Where is your machine position reference?
Is this line uncommented in your firmware?

```
 #define HOMING_FORCE_SET_ORIGIN
```

Grab video with $10=3 in this sequence:
1) Home command $H
2) G90G0X10 command
3) G90G0X-10 command
4) Jog in continious mode X+, X-

**Comment by tistructor** [comment]
Hello,
It is the native firmware of the machine I have not compiled it.
Now the X + axis seems to work continuously but Y and Z don't.
Here is the video:

https://user-images.githubusercontent.com/24445373/146671002-d7d6cac3-84f6-4d50-a647-c7b47b571fa1.mp4

<img width="226" alt="Cattura" src="https://user-images.githubusercontent.com/24445373/146671029-de709b37-a07e-4cf9-9a58-c5824f2eb9b8.PNG">

**Comment by tistructor** [comment]
Homing in this position:
![IMG_20211219_110359](https://user-images.githubusercontent.com/24445373/146671159-f1cfb5f5-8d77-4404-99e1-a21f56450888.jpg)

**Comment by tistructor** [comment]
I have installed this version under linux and I have no problems with jog continuously. 
candle_1.1.7.tar.gz

**Comment by Denvi** [comment]
Try this version please: [Candle_iss527.zip](https://github.com/Denvi/Candle/files/7745457/Candle_iss527.zip)
 
Reference position setting added, should be like following:

![Снимок экрана 2021-12-20 180511](https://user-images.githubusercontent.com/5119037/146771679-f21eb9eb-1e72-4edc-b906-045211f49410.png)

**Comment by tistructor** [comment]
Perfect works well.
Now I am reversing the axes to move Homing the previous position is awkward and dangerous.

**Comment by tistructor** [comment]
X+, Y-, Z-

> Prova questa versione per favore: [Candle_iss527.zip](https://github.com/Denvi/Candle/files/7745457/Candle_iss527.zip)
> 
> L'impostazione della posizione di riferimento aggiunta dovrebbe essere la seguente:
> 
> ![нимок крана 2021-12-20 180511](https://user-images.githubusercontent.com/5119037/146771679-f21eb9eb-1e72-4edc-b906-045211f49410.png)

**Comment by tistructor** [comment]
$3=6

**Comment by tistructor** [comment]
I changed some settings to have Z home with the spindle turret all the way up and again the continuous jog no longer works.

The home is the same as that of the photo with the zero of the z at the top.
x axis increases as you go to the right and y axis increases as the plane moves away.

I tried both the standard beta version and the one attached in zip file but the proplem doesn't fix.

With the stable version 1.1.7 everything works fine.

These are the settings:
$0=10
$1=25
$2=0
$3=4
$4=0
$5=0
$6=0
$10=3
$11=1.000
$12=0.002
$13=0
$20=1
$21=1
$22=1
$23=3
$24=25.000
$25=500.000
$26=25
$27=0.500
$30=1000
$31=0
$32=1
$100=800.000
$101=800.000
$102=800.000
$110=2000.000
$111=2000.000
$112=100.000
$120=20.000
$121=20.000
$122=20.000
$130=313.000
$131=174.000
$132=41.000

**Comment by tistructor** [comment]
Last thing, with the beta version in the part of the window where the work plane is displayed, the tool turret with the correct coordinates is always outside the reference frame.

**Comment by tistructor** [comment]
After several resets, including hardware, the jog with the standard version b does not work continuously.

With the modified B version both X and Y axes work continuously but the Z in positive does not work.

**Comment by tistructor** [comment]
In modified version B, the displayed work plane is incorrect
<img width="414" alt="Cattura" src="https://user-images.githubusercontent.com/24445373/147279870-cb2ce8c4-7e60-4043-a370-d54fc95aa7f4.PNG">

**Comment by Denvi** [comment]
Any illustrations of non-working Z-axis or wrong reference frame?

**Comment by tistructor** [comment]
https://user-images.githubusercontent.com/24445373/147382855-0054699d-9125-469a-a870-a47e4a9f4588.mp4
<img width="452" alt="Cattura" src="https://user-images.githubusercontent.com/24445373/147382901-6acfe5d6-1f34-4a3c-8f02-1c06e1ef2128.PNG">

In my view home should be above as in the real cnc, the X is correct but the Y seems to me reversed.

The video and screenshot are from the version: Candle_iss527.zip

**Comment by tistructor** [comment]
I was wrong to say that the home location was like in the photo above. excuse me

Now the home is this with Z0 at the top:
![IMG_20211225_112602_comp](https://user-images.githubusercontent.com/24445373/147383098-bd0f89cd-513a-4284-a107-aa1abca745a9.jpg)

**Comment by tistructor** [comment]
<img width="720" alt="Cattura" src="https://user-images.githubusercontent.com/24445373/147383305-d019c2cc-6c47-4773-9b6c-f73c3dd7d7bf.PNG">

I'm new with candle I hadn't seen these settings.
I put the Z + over the attached photo and now the Z works continuously too.

<img width="550" alt="Cattura" src="https://user-images.githubusercontent.com/24445373/147383409-a063c5b0-2812-4870-84d2-0e0bcc944728.PNG">

The plane displayed seems wrong to me the y should increase coming down or am I wrong?

Credo di stare sbagliando io ho impostato un sistema di coordinate che non rispetta la regola della mano destra!

**Comment by tistructor** [comment]
My bad.
I fixed the problem after a few tries now it works fine.

$0=10
$1=25
$2=0
$3=6
$4=0
$5=0
$6=0
$10=3
$11=1.000
$12=0.002
$13=0
$20=1
$21=1
$22=1
$23=1
$24=25.000
$25=500.000
$26=25
$27=0.500
$30=1000
$31=0
$32=0
$100=800.000
$101=800.000
$102=800.000
$110=2000.000
$111=2000.000
$112=100.000
$120=20.000
$121=20.000
$122=20.000
$130=313.000
$131=174.000
$132=41.000

<img width="505" alt="Cattura" src="https://user-images.githubusercontent.com/24445373/147385062-c0ccb57e-13fe-4383-8415-772934d5f470.PNG">

<img width="536" alt="Cattura1" src="https://user-images.githubusercontent.com/24445373/147385068-06500d33-ad52-4bde-a504-b8b7266875a4.PNG">

https://user-images.githubusercontent.com/24445373/147385072-38fdf362-36bd-449b-afb8-04a6fda8de58.mp4

**Comment by Denvi** [comment]
I'm glad everything worked out, thank you.
