### ISSUE TITLE
issue with M06 command with  Candle 1.2.13b

### ISSUE THREAD

**Issue by Bart95580** [Denvi/Candle#532]
**Versions**
 - Candle version: 1.2.13b
 - Firmware version:  grbl 1.1f

**PC info**
- OS: … Windows 10
- OpenGL version: ...
### 
**Describe the bug**
With the 1.2.13b version, The M06 command can be intercepted and replaced by user's commands
**That's a nice feature !**

**The issue is :**  By default, when a M06 code is treated, Candle execute a hardcoded script in addition to the user's code.
The additional code executed by Candle is: 
_M3 S10000 
G21 G90 G0 X0 Y0
G1 Z15 F300
G21 G90 G0 F300_

**Why this code is hardcoded ?**

After the **"tool change commands"** user'scode execution, the program is on **"pause"** (French for "On Hold")
If I press the "pause" button, the hardcoded Candle commands are executed before to continue to run the gcode file

The only way to bypass this hardoded code, is to validate the **"Pause on tool change"** check box.
In that case, a message box is displayed for the tool change.
![image](https://user-images.githubusercontent.com/98656764/151670049-faea1f54-3ba0-4a3b-9031-fb117a3f485c.png)

After pressing the **ok** button, the program is on hold, then I must press the **Pause** button  
A new messagebox is displayed with the hardcoded commands Candle is going to execute. 
![image](https://user-images.githubusercontent.com/98656764/151669944-1d2158c3-43ff-4ddf-a244-0e5f900325b8.png)
Then I have to press the **Skip** button to avoid this code execution.
Then the gcode file continue to run...

To Reproduce
The gcode file is generated by Flatcam
Here is my **"Tool change commands"**
![image](https://user-images.githubusercontent.com/98656764/151669991-72eb564a-d816-4a6c-b6ba-699b6f31a0e0.png)

**Expected behavior**
This harcoded code is a pain and must be removed or be optional 

**Screenshots**
![image](https://user-images.githubusercontent.com/98656764/151668938-31e49646-61fb-4521-b952-b70a8210175a.png)

**Comment by Denvi** [comment]
https://github.com/Denvi/Candle/issues/521
