### ISSUE TITLE
Candle 1.2.14/15 problem?

### ISSUE THREAD

**Issue by vladi552** [Denvi/Candle#548]
When the probe commands finished to execute and I press Z+ button, unwanted command are added automatically and move my Z axis to crash (my Z axis can moving up to 100mm max):
```
G21G91 < ok
G38.2Z-30F10 < [PRB:0.000,0.000,-17.360:1]
ok
G0Z0.5 < ok
G38.2Z-2F5 < [PRB:0.000,0.000,-16.975:1]
ok
$J=G21G91X0.000Y0.000Z200.000F500 < ok
```
The command :  G21G91X0.000Y0.000Z200.000F500 out of order! 
This issue not happens in 1.1.92b - it really stable for me.

**Comment by mar0x** [comment]
It seems you faced the issue similar to #542 .
