### ISSUE TITLE
Gcode in probe and command buttons doesnt stay after restart

### ISSUE THREAD

**Issue by Amrt0623** [Denvi/Candle#554]
Is your feature request related to a problem? Please describe.**
After restarting candle i always have to reenter probe and command button gcode

**Describe the solution you'd like**
Some way to save the current gcodes

**Comment by ondras12345** [comment]
These options should be stored in `settings.ini` (probe command is `touchCommand=`).
Try changing some other settings (e.g. visualizer colors). Is the change persistent after restarting Candle?
Which version of Candle are you using? Which operating system?
Do you have write access to the `settings.ini` file?

**Comment by Amrt0623** [comment]
Newbie not a clue. Where do i find settings.ini and touchCommand=
Colours also revert back to orignal.
Version 1.1.8
Mac os high sierra.  Ver10.13.6
No access to settings.ini

**Comment by ondras12345** [comment]
Candle needs to have write access to the directory where `Candle.exe` is, because it needs to create a file called `settings.ini` there.

**Comment by mar0x** [comment]
Hello @Amrt0623 .
- Make sure you have installed Candle to **Applications** (or any other place) and start an _installed_ application (not from opened .dmg archive).
- Was there any application crash messages when you quit from Candle?

**Comment by Amrt0623** [comment]
I am certain i installed all my application.  But i will repeat the process

no crash messages appeared

**Comment by Amrt0623** [comment]
Also i seem to have loose my mm/turn calibration as well

**Comment by Amrt0623** [comment]
Candle app is in the download folder. I have not moved it.  Candle app appears have over written previous last file.  However date modified remains. Jan 3 2020 at 16:54. This predated my first download.   Opened changed colour of tool closed reopened.  Tool reverts to original color

**Comment by Amrt0623** [comment]
Cant find a settings.ini file anywhere???

**Comment by mar0x** [comment]
CH34x_Install_V1.4.pkg - according to the name, it's a driver for USB-serial chip. It maybe required for your board, but not related to Candle application.

settings.ini file should be inside Candle.app directory (Candle.app/Contents/MacOS/settings.ini).

Please calm down and carefully describe your environment and issue(s).
- what is the CNC you are using (model, name, board, URL etc)?
- what is the GRBL firmware version on it?
- where did you get your Candle.app?
- why do you put it in Downloads instead of Applications?

**Comment by Amrt0623** [comment]
Genmitsu proverxl  
Grbl 1.1 compatible 
Aurduino board cant more data
Download from sainsmart.  ( could re download installer)
Installer gives option but says don’t change default locations. Thats where it went.

Issue is that no changes i make in preferences return after closing and then restarting candle

**Comment by mar0x** [comment]
Please share the link to installer for investigation or use "unofficial" [Candle-1.1.9.dmg](https://github.com/mar0x/Candle/releases/download/v1.1.9/Candle-1.1.9.dmg) - open it and copy Candle.app to your favourite location.

**Comment by Amrt0623** [comment]
K tried to open candle app.  Wont open just runs.  So no access to settings.ini

will try candle-1.1.9.dmg

**Comment by mar0x** [comment]
I've read [the instructions](https://docs.sainsmart.com/article/zcyhab7a0k-how-to-install-grblcontrol-candle-for-mac) and after candle.dmg open should be Candle.app **copy** to Applications or any other place.

**Comment by Amrt0623** [comment]
https://docs.sainsmart.com/article/vdgvaufcu1-genmitsu-prover-xl-4030-resources

Scroll down

**Comment by Amrt0623** [comment]
Found settings.ini.    Aaah

**Comment by Amrt0623** [comment]
So saved an original copy and will modify settings.ini.   With my updates.  Hooe it gies well.   Thank you very much

**Comment by Amrt0623** [comment]
K copied gcodes userCommands0,1,2,3
G code is approximently the same length as z probe command.  
Z probe command change is retained

But when i open candle.  I only get the first two codes in the buttons G21G91 so no action when pressed

Also changed port to tty.wchusbderial430. But it was not retained either?

**Comment by Amrt0623** [comment]
Got it added quotes. Wow didnt think i was ever gonna get this. So much thx

**Comment by ondras12345** [comment]
You shouldn't need to edit `settings.ini` by hand. If the permission in the filesystem are set correctly, Candle should be able to modify it automatically.

**Comment by mar0x** [comment]
The thing is the information about `settings.ini` and permissions is too technical and it was provided too early, prior the issue analysis. The real issue was (I suppose) in incorrect Candle.app installation (the absence of installation, to be precise).
