### ISSUE TITLE
Height map - Scanning Error

### ISSUE THREAD

**Issue by ArturoPin** [Denvi/Candle#563]
**Versions**
 - Candle version: 1.1.7 and Candle 1.2.15b x64
 - Firmware version: 1.1

**PC info**
- OS: Windows 10 Home Single Language, Version: 21H2
- OpenGL version: 4.6

**Describe the bug**
After the scanning process of the heightmap the values remain as "nan".

I have an issue when I generate the Heightmap, I create a new one, set the dimensions, and I clic on the Probe button to start the scanning process. This begins and ends without displaying any error. But all values of the heightmap remain as nan.

**To Reproduce**
1. Set the Origen
2.  Open a *.nc file
3. Clic on the "Create" button on the Heightmap menu
4. Set the Heightmap settings 
![image](https://user-images.githubusercontent.com/108427523/176511036-8033410e-eb45-4a2e-b671-c20f2f0d87c8.png)
5. Clic on the "Probe" button
6. The Scanning process begins
7.  The message "Job done" pops up after the scanning ended up. (The heightmap values remains as "nan")

**Expected behavior**
I expected to see the values stored while the scanning is being executed or at least when the scanning has already finished.

**Screenshots**
![image](https://user-images.githubusercontent.com/108427523/176511865-10d6f66b-661e-4e71-b875-a99b8ca5aca4.png)

**Additional context**
I have tried on different versions of candle 1.1.X and 1.2.X but this issue is present on all.

**Comment by muhammadelmogy** [comment]
Under **settings ->Heightmap**: make sure **heightmap probing feed** is set to a proper value and is not empty! for example 20

**Comment by ArturoPin** [comment]
> 

It is set to a value of 10
![image](https://user-images.githubusercontent.com/108427523/176543052-b7a1717a-cb5e-4e24-8143-84fe1f3a8bf3.png)

**Comment by mar0x** [comment]
Hello.
Please
1. enable console output for commands;
2. make sure Z-probe command configured;
3. connect your probe tool;
4. make sure letter "P" appears at the top-left corner of 3D view when you manually touch the probe;
5.  perform a single manual Z probe.

I assume the tool starts moving down until it touches the probe.
Please share the Z-probe command and complete output to console window.

**Comment by ArturoPin** [comment]
Hello

I'm new on this topics, but I hope I did what you said.


1. 1.Using a serial monitor I sent the code "G21G91G38.2Z-30F100"

**Comment by ArturoPin** [comment]
Hello,

First of all, Thanks for your help. I'm new on this, but I hope I did what you said.

1.  Using a serial monitor, I sent the code "G21G91G38.2Z-30F100".
2. The router started to move on the z axis, until I performed a manual Z-probe.
3. The router stopped but I didn't receive the letter "P", instead of it, I received only an OK.
![image](https://user-images.githubusercontent.com/108427523/176945540-f43a04ce-2a6b-4ba6-ab84-7e7966eb32de.png)
5. I repeated the same on Candle and I got the same
![image](https://user-images.githubusercontent.com/108427523/176945741-27e9d756-5b19-432f-a180-a536fa717669.png)

Do you know what I can do?

**Comment by ArturoPin** [comment]
I don't know if it can help but my settings are:
Grbl 1.1f ['$' for help]
$0=10
$1=25
$2=0
$3=6
$4=0
$5=0
$6=0
$10=1
$11=0.010
$12=0.002
$13=0
$20=0
$21=1
$22=0
$23=0
$24=25.000
$25=500.000
$26=250
$27=1.000
$30=1000
$31=0
$32=0
$100=400.000
$101=400.000
$102=400.000
$110=800.000
$111=800.000
$112=500.000
$120=500.000
$121=500.000
$122=500.000
$130=180.000
$131=300.000
$132=45.000
ok

**Comment by mar0x** [comment]
It seems something wrong with your firmware. Here is what my console output for the probe:
```
G21G91G38.2Z-20F10 < [PRB:0.000,0.000,-22.951:1]
ok
```
Regarding 'P' letter. It normally appears in main 3D view window when you touch the probe:
<img width="330" alt="Screenshot 2022-07-01 at 21 04 50" src="https://user-images.githubusercontent.com/17641893/176949971-0e38eb42-ec09-4ecb-86c3-f7919b5750b4.png">

Candle constantly send '?' request and get the status back. This is the output from terminal (the lines started from '>' is my input and not displayed actually):

```
Grbl 1.1f ['$' for help]
> ?
<Idle|MPos:0.000,0.000,0.000|FS:0,0|WCO:0.000,0.000,0.000>
> ?
<Idle|MPos:0.000,0.000,0.000|FS:0,0|Ov:100,100,100>
> ?
<Idle|MPos:0.000,0.000,0.000|FS:0,0|Pn:P>
> G21G91G38.2Z-20F10
[PRB:0.000,0.000,-0.598:1]
ok
> ?
<Idle|MPos:0.000,0.000,-0.605|FS:0,0|WCO:0.000,0.000,0.000>
```

During height map probe Candle relies on `[PRB:0.000,0.000,-0.598:1]` response and get Z position from this response.

As soon as your vendor said the machine unable to probe, he maybe knows something we don't know regarding the actual firmware of schematic of your board :)

**Comment by mar0x** [comment]
Regarding your GRBL settings I would say the accelerations are pretty high ($120, $121, $122).

Also the travel over Z axis is 45mm ($132) and the hard limits are enabled ($21). Maybe the probe position is out of limits? Try to disable the hard limits ($21=0) and repeat the test.

Check the defaults here: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration .

**Comment by ArturoPin** [comment]
> It seems something wrong with your firmware. Here is my console output for the probe:
> 
> ```
> G21G91G38.2Z-20F10 < [PRB:0.000,0.000,-22.951:1]
> ok
> ```
> 
> Regarding 'P' letter. It normally appears in main 3D view window when you touch the probe: <img alt="Screenshot 2022-07-01 at 21 04 50" width="330" src="https://user-images.githubusercontent.com/17641893/176949971-0e38eb42-ec09-4ecb-86c3-f7919b5750b4.png">
> 
> Candle constantly send '?' request and get the status back. This is the output from terminal (the lines started from '>' is my input and not displayed actually):
> 
> ```
> Grbl 1.1f ['$' for help]
> > ?
> <Idle|MPos:0.000,0.000,0.000|FS:0,0|WCO:0.000,0.000,0.000>
> > ?
> <Idle|MPos:0.000,0.000,0.000|FS:0,0|Ov:100,100,100>
> > ?
> <Idle|MPos:0.000,0.000,0.000|FS:0,0|Pn:P>
> > G21G91G38.2Z-20F10
> [PRB:0.000,0.000,-0.598:1]
> ok
> > ?
> <Idle|MPos:0.000,0.000,-0.605|FS:0,0|WCO:0.000,0.000,0.000>
> ```
> 
> During height map probe Candle relies on `[PRB:0.000,0.000,-0.598:1]` response and get Z position from this response.
> 
> As soon as your vendor said the machine unable to probe, he maybe knows something we don't know regarding the actual firmware or schematic of your board :)

I thought the same about the firmware. I did an upgrade to GRBL 1.1h and the problem was gone.

**Comment by Igven** [comment]
Hello. I have same problem. Please give me link how upgrade cnc.
