### ISSUE TITLE
Bug: Personalizing the interface Candle 1.2.15b

### ISSUE THREAD

**Issue by ArturoPin** [Denvi/Candle#565]
**Versions**
 - Candle version: Candle 1.2.15b
 - Firmware version: 1.1h

**PC info**
- OS: Windows 10 Home Single Language, Version: 21H2
- OpenGL version: version: 4.6

**Describe the bug**
I would like to personalize my Candle 1.2.15b interface, that's included on this version. But the changes are not saved when close. (when I open candle again It is as default.)

How I would like to have it:
![image](https://user-images.githubusercontent.com/108427523/177024605-b8099f50-0949-448f-868f-a5267c581353.png)

When I open it again:
![image](https://user-images.githubusercontent.com/108427523/177024578-3983e4c5-c8e7-4be8-8bfb-693f6ca95380.png)

**Comment by mar0x** [comment]
@ArturoPin please describe how did you installed the Candle, how do you usually start it and what happens when you close it (maybe there is a message about application crash?)

**Comment by mar0x** [comment]
@ondras12345 What is the **typical** sequence of Candle installation which should lead to absence of write permissions?

**Comment by ondras12345** [comment]
> What is the **typical** sequence of Candle installation which should lead to write permissions absence?

Unzip as administrator to Program Files and try to run as a regular user. I haven't used Windows for a few years now, but i vaguely remember something like that happened to me.

**Comment by mar0x** [comment]
@ondras12345 "Unzip as Administrator" is not the **typical** case for Windows 10 Home, don't you think?

"Running _directly_ from ZIP" - is what I'm expecting to get as an answer. Permissions is not an issue and the suggestion to check the permissions is confusing.

**Comment by rjcamatos** [comment]
Extracting to Programa Files folder it Will adquire the permisions of that
folder, by default no site to users.

A terça, 5/07/2022, 10:01, ondras12345 ***@***.***> escreveu:

**Comment by ArturoPin** [comment]
You were right, all what I need to do was running the SW as administrator. Thanks
