### ISSUE TITLE
When removing the height map, the machine stops

### ISSUE THREAD

**Issue by RuslanLLLLL** [Denvi/Candle#579]
Hello everyone!
Error unknown to science!

**Versions**
 - Candle version: , 1.1.7, 
 - Firmware version: 1.1

Windows10

When removing the height map, the machine stops each time at the last point of the first pass along the X axis. The result is repeated over and over again. All other machine functions work.
I reinstalled the Candle program, the Arduino firmware too. Nothing changed.

Help me please

![изображение_viber_2022-10-16_14-05-28-612](https://user-images.githubusercontent.com/115867317/196033684-9218f2a6-80d0-48ea-9d5c-6da177db423b.jpg)
![изображение_viber_2022-10-16_14-05-28-831](https://user-images.githubusercontent.com/115867317/196033693-01e548ff-6db4-4942-a40d-a4f9694068e3.jpg)
![изображение_viber_2022-10-16_14-05-29-222](https://user-images.githubusercontent.com/115867317/196033708-2e713387-9af0-4bd7-b28f-8f0e42302cd6.jpg)
![изображение_viber_2022-10-16_14-05-29-287](https://user-images.githubusercontent.com/115867317/196033718-2e7c79b9-91c2-4c62-aafc-7c2ae5884c86.jpg)

![изображение_viber_2022-10-16_14-05-29-335](https://user-images.githubusercontent.com/115867317/196033738-925511ff-6f41-43ea-aec9-428af41d3118.jpg)

**Comment by mar0x** [comment]
Hello,

Please describe sequence of operation step-by-step, share your gcode program and produced heightmap (if any).

It would be good to have an information regarding "error: 9" you probably can see at the issue description as well.

**Comment by mar0x** [comment]
According to the screenshot 2:
"ALARM: 2" - most likely triggered from [grbl/protocol.c:224](https://github.com/gnea/grbl/blob/bfb67f0c7963fe3ce4aaf8a97f9009ea5a8db36e/grbl/protocol.c#L224) which is in turn caused by [grbl/limits.c:426](https://github.com/gnea/grbl/blob/bfb67f0c7963fe3ce4aaf8a97f9009ea5a8db36e/grbl/limits.c#L426).

[Soft limit](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#20---soft-limits-boolean) is reached and triggered this alarm. I would suggest to check the limit settings.

This is definitely NOT the [grbl issue](https://github.com/gnea/grbl/issues/1169).

**Comment by mar0x** [comment]
It is hard to guess what's going on without complete information about coordinates, send commands and received responses.

Try to record the communication between Candle and CNC serial port using serial port monitor.

**Comment by RuslanLLLLL** [comment]
Hi,
I did some work here...
Look please.
step by step
![Остановка0](https://user-images.githubusercontent.com/115867317/196419135-00d24699-116b-4931-a8de-80e827389a70.png)
![Остановка1](https://user-images.githubusercontent.com/115867317/196419155-197044cc-b9a0-43ad-a382-4d515e899e1b.png)
![Остановка2](https://user-images.githubusercontent.com/115867317/196419172-482c3f7e-f28c-482e-9da0-16bf80525074.png)
![Остановка3](https://user-images.githubusercontent.com/115867317/196419195-934395a7-5aa0-496c-a254-2dd614ca2e4a.png)

**Comment by mar0x** [comment]
Could you please provide serial port communication dump file instead of comics.

**Comment by RuslanLLLLL** [comment]
The problem is solved by changing the parameter $20=1 to $20=0.
I wish you all success!
