### ISSUE TITLE
heightmap

### ISSUE THREAD

**Issue by kusacius** [Denvi/Candle#585]
**Versions**
 - Candle version: 1.2.9b

**PC info**
- OS: windows 7

**Describe the bug**
when checking "use heightmap", g-code is breaking.

**To Reproduce**
1. Open g-code "1_skyles.ngc" or "Panele4Test_viskas_be_borderio.ngc"
2. Open heightmap file "panele.map"
3. Click on 'use heghtmap'

**Screenshots**
![original](https://user-images.githubusercontent.com/119690600/205343218-31bdcc5c-1315-4775-8a7c-e4b67a0b9750.jpg)
![with_heightmap](https://user-images.githubusercontent.com/119690600/205343257-50279e4e-913b-4a3d-952f-ce765d64bfa3.jpg)
![original1](https://user-images.githubusercontent.com/119690600/205345089-58ff4c42-c4c4-4726-9b76-5e5a8834f8d9.jpg)
![with_heightmap1](https://user-images.githubusercontent.com/119690600/205345113-8f51c7b7-70ac-4cb1-939b-15c4b90aea04.jpg)

**Example files**
Add G-code files that cause problems.
[test.zip](https://github.com/Denvi/Candle/files/10142858/test.zip)

**Additional context**
strange interpreting arcs in g-code
tested on same other candle versions, problem the same.
[test1.zip](https://github.com/Denvi/Candle/files/10145321/test1.zip)

**Comment by mar0x** [comment]
Hello,
1. Could you please share the heightmap file (when in heightmap "Edit mode", choose "File"->"Save");
2. I'm unable to reproduce the issue with my heightmap on the version I'm currently using: https://github.com/mar0x/Candle/releases/tag/v1.1.9 - please try;

**Comment by kusacius** [comment]
[test1.zip](https://github.com/Denvi/Candle/files/10145229/test1.zip)
thank you for quick response, and sorry for my english, i  am from not existing ussr, and my russian is better. i send wrong zip file, this one is right. and i worked on my problem, and solved with correcting gcode syntax. my gcode is generated from altium dxf file to gcode with dxf2gcode utility, i corrected converted gcode files, and attacihng them in next message. i dont know, without heighmap these files are working. so syntax may be is normal. but i maked changes i these files, and they now is working with heigtmap

**Comment by kusacius** [comment]
[test2.zip](https://github.com/Denvi/Candle/files/10145272/test2.zip)
there are my changed previous files, and now they working. so i dont know where the problem, in candle heightmap or in dxf2gcode syntax.
