### ISSUE TITLE
Home key doesn’t work

### ISSUE THREAD

**Issue by Amrt0623** [Denvi/Candle#606]
**Versions**
 - Candle version: 1.22.15b
 - Firmware version: 1.1h
- Windows 11

when i press the home icon.  The z axis moves downward about 10mm (step size in jog command), and the status changes to alarm, and the machine and work space coords stay the same. (0,0,-3)
When i press the home icon without clearing the alarm the same thing happens again
Console shows:
$h <alarm:8
Ok
Grbl 1.1h [$ for help]
[MSG:Check Limits]
[MSG:$H$X to unlock]
s3400<error:9

restore origin works.  Set xy sat z works
 
 limit switches work
 
I changed from NO mechanical limit switches to photoelectric switches didnot change $5=0

machine works normally otherwise.   

I dowloaded and reinstalled candle no change

**To Reproduce**

**Expected behavior**

**Screenshots**

**Example files**
Add G-code files that cause problems.

**Additional context**

**Comment by ondras12345** [comment]
|ID|Alarm Code Description|
|--|--|
| 8 | Homing fail. Cycle failed to clear limit switch when pulling off. Try increasing pull-off setting or check wiring. |


https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface#alarm-message

**Comment by Amrt0623** [comment]
Thanks. 
i checked the limit switches. Xyz have indicator lights on the board.
When i activate any of the limit switches the correct light on the board changes to on.  That is what is supposed to happen.

**Comment by Amrt0623** [comment]
So i toggled $5 from 0 to 1 and back.  I had the $21=0
Now the homing cycle works
  But of course the limit switches didn’t work
I set $21 back to 1 and now all works

I had increased the pull of from 3 to 5.  But until i toggled $5 back and forth that didn’t help

the problem seems to be something in the software somwhere?

hoping it never happens again

**Comment by Amrt0623** [comment]
Damn. Massivly screw up again

**Comment by Amrt0623** [comment]
Finally.  It was picking up different settings files.   

Serious deleting reload reset go
