### ISSUE TITLE
Sending File after Height Map 

### ISSUE THREAD

**Issue by kturunen** [Denvi/Candle#607]
**Versions**
 - Candle version: [1.1.7

**PC info**
- OS:Windows 10

**Describe the bug**
![destroyedPCB](https://github.com/Denvi/Candle/assets/134768313/9d8d0e62-a2e0-4997-a053-cface96d02ea)

Experienced a broken PCB after making a HeightMap
The last command after HeightMap was Send File 
Why does Z  NOT move up before returning to Home Position?

**Comment by mar0x** [comment]
Hello,
How far up it should move? 3 mm? 30 mm? 50 mm?

**Comment by kturunen** [comment]
More than heighest point in the height map.

**Comment by mar0x** [comment]
I would suggest to add initial movement to safe position in your gcode.

**Comment by kturunen** [comment]
After redoing this, I have to wonder how I managed to scratch my fr4. The safe position was set high enough and HeightMapping does return to safe. Maybe I was careless..
This may be closed. Thanks all.
