### ISSUE TITLE
Problem with the heightmap data

### ISSUE THREAD

**Issue by currete2007** [Denvi/Candle#616]
Version of candle: 1.1.7
openGL: 4.6
grbl 1.1f
machine: Robo CNC router 3018

probe orders: G21G91G38.2Z-30F100; G0Z1; G38.2Z-2F10

I have a problem when creating the height maps, the height map is doing it but it is not saving the height data and when it finishes measuring it is all blank.

I tried the experimental version and reinstalled V1.1.7 but the same thing still happens

and when initiating a cut/engraving with a milling cutter, when it reaches command 30, which is M6, it throws an error(error:20). It lets me ignore it and continue, I don't know if it has something to do with it or what it means

**Comment by mar0x** [comment]
Hello,
Please send the command "G21G91G38.2Z-30F100" using console window (probe should move down, touch the surface and stop), then share exact CNC responses in console.

**Comment by currete2007** [comment]
this is what it says 

[CTRL+X] < Grbl 1.1f ['$' for help]
G21G91G38.2Z-30F100 < ok

**Comment by mar0x** [comment]
This is weird.

Please confirm:
1. Immediately after the command send the probe moves down
2. ... touches the surface ...
3. ... and stops
4. "PS: P" appears at the top left corner of G-code visualization window when the probe touches the surface
5. "Status" changes from "Idle" to "Run" and then back to "Idle"

I'm (and Candle) expecting something like
```
G21G91G38.2Z-30F100 < [PRB:0.000,0.000,-4.608:1]
ok
```
as the response for the G38.2 command.

**Comment by currete2007** [comment]
Is there a problem if I wait until Thursday to answer? Now I am not available to use the machine.

**Comment by mar0x** [comment]
No problem. This is your machine and your issue :) I'm unable to answer instantly as well.

**Comment by currete2007** [comment]
1. Yes
2. Yes
3. Yes
4. Yes
5. Yes

**Comment by mar0x** [comment]
So, the probe works normally except the response. To be 100% it would be perfect to test it with simple serial port console (for instance from Arduino IDE): connect, see the prompt and send exactly one line "G21G91G38.2Z-30F100" and check the answer.

Is it possible your machine has modified grbl firmware?

**Comment by currete2007** [comment]
I don't know what board to put in the arduino ide so that it can detect it

**Comment by currete2007** [comment]
then what should I do?

**Comment by mar0x** [comment]
> I downloaded the grbl source code from github ..
Have you upgrade the router firmware?

**Comment by mar0x** [comment]
> then what should I do?

I would suggest to contact CNC vendor and ask for solution with this issue.

If you feel you understand how to upgrade your router firmware - you can try to upgrade to version 1.1h . I would recommend to backup existing firmware if you able to.

**Comment by currete2007** [comment]
> > Descargué el código fuente de grbl de github.
> 
> ¿Has actualizado el firmware del enrutador?

No

**Comment by currete2007** [comment]
> > ¿entonces, qué debería hacer?
> 
> Sugeriría contactar al proveedor de CNC y solicitar una solución a este problema.
> 
> Si cree que comprende cómo actualizar el firmware de su enrutador, puede intentar actualizar a la versión 1.1h. Recomendaría hacer una copia de seguridad del firmware existente si es posible.

I'll try

**Comment by mar0x** [comment]
Without `[PRB..` response it impossible to use Candle auto heightmap functionality.
I'm sorry cannot help you with CNC upgrade because I have no schematic and implementation details of the machine. 

Maybe someone else here have any idea?

**Comment by currete2007** [comment]
I got it!!! update the firmware with avdubess to grbl 1.1h and now it gives me a response PRB C:

**Comment by papillion47** [comment]
GRBL de Heightmap veya visualizer kısmı çalışmıyor. Tam ve doğru yapılmış ayarlarımla uzun zamandır 3018 cihazım ve GRBL normal çalışıyordu. 1-2 ay ara verip yeniden çalışmaya koyulduğumda ne olduysa visualizer ekranı boş ve işlevsiz olarak karşıma çıktı. GRBL nin diğer bütün fonksiyonları doğru çalışıyor. GRBL yi defalarca silip-kaldırıp yeniden yüklemem de işe yaramadı.  ( Not: Eski PC' mde de yüklü olan GRBL normal çalışıyor. Daha hızlı çalışan yeni PC de yüklü olan da ise bu sorun çıktı. Yani demek ki CNC cihazımda ve ona yapılmış ayarlarımda bir sorun yok.) Sorunun neden ve nerede olduğunu bilen olur da çözüm için yol gösterirse çok mutlu olacağım. Saygı ve selâmlarla..

**Comment by mar0x** [comment]
@papillion47 Try to install recent Candle version ( https://github.com/Denvi/Candle/releases/tag/v1.1 ) or more recent buld ( https://github.com/mar0x/Candle/releases/tag/v1.1.9 ).

**Comment by papillion47** [comment]
Uygun olduğunu düşünerek [Candle-1.1.9-Win-64bit.zip](https://github.com/mar0x/Candle/releases/download/v1.1.9/Candle-1.1.9-Win-64bit.zip) yükledim. Heightmap çalıştı, visualizer doğru gösteriyor. Fakat bu defa "jog" komutları çalışmıyor. yön butonlarının ortasında aktif olmadığını gösteren işaret var. Ekran resmi aşağıda. Umarım buna da bir çözüm gösterirsiniz. Sevgi ve selâmlarla..
![candle ekranı](https://github.com/user-attachments/assets/9c1ec616-230c-4e50-9ab3-3d64024d4320)
