### ISSUE TITLE
Cnc works randomly when send g-code

### ISSUE THREAD

**Issue by Wita-blip** [Denvi/Candle#649]
**Versions**
 - Candle version: 1.0.11
 - Firmware version: 0.9j

**PC info**
- OS:windows 10 64bit
- OpenGL version: idk

**Describe the bug**
candle 1.01.1 looks good, manual jogging works fine, homing is good, manual jogging works fine, after i set X0, Y 0 and Z0 and i click send, cnc runs randomly. os window 10 64bit, grbl 0.9j, candle 1.0.1.1, need help

**Comment by Wita-blip** [comment]
when using candle 1.0.10 vizualizer getting blank but manual jogging, homing works fine

**Comment by Wita-blip** [comment]
@Denvi  need help

**Comment by mar0x** [comment]
Hello,
You are using outdated GRBL firmware version and this forces you to stay on outdated Candle version.
Try latest Candle 1.1.7+ without CNC connect (visualizer). If it works, I would recommend to upgrade your CNC firmware up to 1.1h and use latest Candle 1.1.7+.

**Comment by Wita-blip** [comment]
ok, i will try it, thanks for the info

**Comment by Wita-blip** [comment]
I will let you know the result, thank you very much for the information

**Comment by Wita-blip** [comment]
![IMG_20220518_005721](https://github.com/user-attachments/assets/4b23373e-fd19-4645-8249-42772eccae50)

**Comment by Wita-blip** [comment]
one more question, I bought a cnc with a control board from the manufacturer as pictured (firmware grbl 0.9j) can the control board as pictured be updated to grbl 1.1 firmware? if possible, what should I choose? (Is it arduino uno or arduino nano)

**Comment by Wita-blip** [comment]
![Uploading IMG_20220518_005712.jpg…]()

**Comment by mar0x** [comment]
As far as I can see, this is not an Arduino board (Uno nor Nano), but CNC controller.

Could you please share exact board (CNC) name and version, maybe URL with the information (online store, vendor site etc).

If you find upgrade instructions on the vendor site or get it directly from the support, this would be perfect.

Complete detailed board photo may also help (exact symbols from the square 32pin chip required).

**Comment by Wita-blip** [comment]
Ok, wait a minute

**Comment by Hostaler** [comment]
> Hola, está utilizando una versión de firmware GRBL obsoleta y esto lo obliga a permanecer en la versión obsoleta de Candle. Pruebe la última versión de Candle 1.1.7+ sin conexión CNC (visualizador). Si funciona, recomendaría actualizar el firmware de su CNC hasta 1.1h y utilizar la última versión de Candle 1.1.7+.

Es mejor la version 1.1.7 que la que yo tengo? Yo tengo la 1.2.15b

![Captura de pantalla 2024-10-23 151844](https://github.com/user-attachments/assets/16ebba91-c36d-42dc-a48c-cdc63ce52b9c)

**Comment by Wita-blip** [comment]
![Uploading IMG20241023193036.jpg…]()

**Comment by Wita-blip** [comment]
![Uploading IMG20241023192757.jpg…]()

**Comment by Wita-blip** [comment]
this is the clearest photo i could get

**Comment by Wita-blip** [comment]
Could you please share exact board (CNC) name and version, maybe URL with the information (online store, vendor site etc).

If you find upgrade instructions on the vendor site or get it directly from the support, this would be perfect.

Answer: 
i don't have the info, but i like this control board because it can directly power a 48v spindle with the addition of a dc to dc step up board and easy to handle, just follow the information on the control board for installing limit switches, DC cooling fans, installing 48v spindles with only one power supply`

**Comment by Wita-blip** [comment]
Cnc 3018

**Comment by Wita-blip** [comment]
written on ic atmel mega 328p u-th 354730 1924he or 1924me

**Comment by Wita-blip** [comment]
I just tested my cnc with candle 1.0.12, now I know what causes the random aefara movement, namely the z probe, after X0y0 I do a probe, after the probe I give the command G0x20y20, it moves according to the command, but once I give the command G0X0Y0 it doesn't move at all with the coordinate command given below the number 20 (X20 Y20), after I exit the candle and re-enter, I manually determine the Z0 point, it works normally even with the g code file that will be worked on, it works normally, what should I do so that I can use the z probe to determine the Z0 point not manually

**Comment by Wita-blip** [comment]
I just tested my cnc with candle 1.0.12, now I know what causes it to move randomly, namely the z probe, after X0y0 I do a probe, after the probe I give the command G0x20y20, it moves according to the command, but once I give the command G0X0Y0 it doesn't move at all with the coordinate command given below the number 20 (X20 Y20), after I exit the candle and re-enter, I manually determine the Z0 point, it works normally even with the g code file that will be worked on, it works normally, what should I do so that I can use the z probe to determine the Z0 point not manually

**Comment by mar0x** [comment]
> Is version 1.1.7 better than the one I have? I have 1.2.15b

@Hostaler best version is the version which works for you and covers your requirements :)

1.1.7 is definitely better than 1.0.11 which seems not perfect for author of this issue. 1.2 is experimental version this why I'm not recommend it.

**Comment by mar0x** [comment]
@Wita-blip only first photo uploaded successfully.
"CNC 3018" only describe the size of the working area 30 cm x 18 cm
"atmega 328p" is important information;
Your board upgrade capabilities depends on current board firmware. Firmware with bootloader is easier to upgrade.

**Comment by Wita-blip** [comment]
1.1.7 is not imperfect for me, I just compensate for what I have for now that I can fit the control board which is grbl 0.9j so I can only use candle 1.0x and I also don't know how to update the firmware, I'm still learning it

**Comment by Wita-blip** [comment]
![IMG-20241023-WA0008](https://github.com/user-attachments/assets/fa2047b9-e11b-4f1a-a216-8cf992b72810)

**Comment by Wita-blip** [comment]
![Uploading IMG20241023192757.jpg…]()

**Comment by Wita-blip** [comment]
![IMG20241023192757](https://github.com/user-attachments/assets/b6537097-428a-48bf-bbfb-66e50e5b0761)

**Comment by Wita-blip** [comment]
![20241024_000127](https://github.com/user-attachments/assets/2b51ed29-f64a-4982-a1e6-65ac50b62916)

**Comment by Wita-blip** [comment]
just bought an arduino uno with cnc shield for firmware upgrade
