### ISSUE TITLE
Смена языка/Translations

### ISSUE THREAD

**Issue by DrGrbl** [Denvi/Candle#73]
Как сменить язык?

**Comment by Denvi** [comment]
Язык программы устанавливается автоматически в соответствии с системной настройкой "Язык системы".

**Comment by DrGrbl** [comment]
А вручную можна изменить? Например, что бы язык системы был английский, а язык программы русский.

**Comment by Denvi** [comment]
> системной настройкой "Язык системы".

Настройкой "Формат" региональных стандартов.

> язык системы был английский, а язык программы русский.

Переименуйте файлы "grblControl_ru.qm" и "qt_ru.qm", находящиеся в папке "translations", в "grblControl_en.qm" и "qt_en.qm" соответственно.

**Comment by DrGrbl** [comment]
Спасибо, все работает!
Но, есть, к примеру, g-код (см. вложение), обработка по коду работает, но визуализации нет, не видно траектории! В других программах все показывает.

[Hello.zip](https://github.com/Denvi/grblControl/files/481033/Hello.zip)

**Comment by Denvi** [comment]
Описывалось здесь #26.
В вашей траектории не установлена координата Z.
