### ISSUE TITLE
G4 P**

### ISSUE THREAD

**Issue by Rom327** [Denvi/Candle#74]
Hi! Try to run grblControl 0.8.4 to control a laser engraver. I noticed that the G4 P**\* works in seconds. Standard should work in milliseconds. Or maybe I'm wrong?
Привет! Пытаюсь запустить  grblControl 0.8.4 для управления лазерным гравером. Заметил, что команда G4 P**\* отрабатывает в секундах. По стандарту должно отрабатывать в миллисекундах. Или может я ошибаюсь?

**Comment by Denvi** [comment]
Hello, GRBL uses seconds in argument of G4 Px command with accordance to rs274 standard.
So, to set dwell to 10 ms, we should use fraction:

~~~
G4 P.01
~~~
