### ISSUE TITLE
Candle v1.0 будет ли скомпилированная под Linux 

### ISSUE THREAD

**Issue by SadovovAlex** [Denvi/Candle#80]
Доброго времени суток.

Будет ли скомпилированная версия под Linux mint/ubuntu ?

Вопрос возник так как мне вроде бы удалось скомпилировать из исходников, хотелось бы сразу готовую версию, без установки QT и компиляции

**Comment by schpuntik** [comment]
Я тут собирал  но пока  не пробывал. Так как  не собрал  пока принтер. Могу  скинуть тест.

**Comment by Denvi** [comment]
Привет. Будет чуть позже.

**Comment by Werwolfx** [comment]
Thanks.  i will wait =)

**Comment by Denvi** [comment]
Compiled for x64: [candle_1.0.7.tar.gz](https://github.com/Denvi/Candle/releases/download/v1.0/Candle_1.0.7.tar.gz)

**Comment by SadovovAlex** [comment]
Thank you
