### ISSUE TITLE
Fix for MAC OS X

### ISSUE THREAD

**Issue by skhalipa** [Denvi/Candle#81]
**NOTE:** 
While compile application for mac os x El Capitan, i have error: 
/Candle-master/src/frmmain.h:65: error: exception specification of overriding function is more lax than base version
    const char* what() const //_GLIBCXX_USE_NOEXCEPT
                ^
**FIX:** 
Please replace code block: 

**FROM:**
```
class CancelException : public std::exception {
public:
    const char* what() const _GLIBCXX_USE_NOEXCEPT
    {
        return "Operation was cancelled by user";
    }
};
```

**TO:**

```
class CancelException : public std::exception {
public:
#ifdef Q_OS_MAC
#undef _GLIBCXX_USE_NOEXCEPT
#define _GLIBCXX_USE_NOEXCEPT _NOEXCEPT
#endif

    const char* what() const _GLIBCXX_USE_NOEXCEPT
    {
        return "Operation was cancelled by user";
    }
};
```

**Comment by Denvi** [comment]
Done. Thank you.
