### ISSUE TITLE
Windows: candle_1.1.zip

### ISSUE THREAD

**Issue by Peter6891** [Denvi/Candle#87]
Hello!
Have download new version candle_1.1.zip for windows... But it is not run on my operating system (Windows XP SP3)

**Comment by Denvi** [comment]
Any error messages? Tested just now on Windows XP SP3 (VirtualBox guest), works fine.

**Comment by Peter6891** [comment]
I unzipped the file (candle_1.1.zip), which is downloaded from the website to a folder C:Programm Files\Candle 1.1\
And it isn't run... Message: "Programm does not run!"

**Comment by Peter6891** [comment]
(sorry for my English)

**Comment by Peter6891** [comment]
may be needed for the program to even some components of the windows were installed?

**Comment by Denvi** [comment]
Try [vcredist_x86.exe](https://www.microsoft.com/ru-RU/download/details.aspx?id=40784) please.

**Comment by Peter6891** [comment]
installed - did not help. at home more try ...

**Comment by Peter6891** [comment]
home installed the program - it works ... (operating system such as windows xp)

**Comment by starline** [comment]
добрый день!

У меня тоже наблюдается такая проблема на разных компьютерах под управлением Windows XP 32 Бита

Программа не можем запуститься с вылетом окошка Message: "Programm does not run!"

**Comment by Peter6891** [comment]
на следующий день программа запускается и нормально работает(на тех компьютерах, на которые устанавливалась но сразу не заработала, а вылетала с окном "Программа не запускается"). причина мне не известна. возможно что это проблема с самой операционной системой - может позже что-то обновляется и после перезапуска в определённый момент запускается...

**Comment by starline** [comment]
Хорошо бы разобраться почему так
На другом компьютере с такой же операционной словил ошибку при запуске.
"Ошибка при инициализации приложения 0xс00000 1d"

**Comment by starline** [comment]
Отвечаю сам на свой вопрос.
По ошибке нашел следующую информацию 

> Проблема в том, что процессор на данном ПК не поддерживает SSE2 - http://en.wikipedia.org/wiki/SSE2

**Comment by Peter6891** [comment]
я же говорю - установил программу - не запускалась. оставил установленную. на следующий день уже не переустанавливал - она со вчера установлена была. просто запустил - запустилась. при дальнейших запусках всегда запускалась. и так на трёх компах.

**Comment by Denvi** [comment]
> как это можно исправить? Ну кроме как заменить железо )

Пересобрать Qt без поддержки SSE2. Если это вообще реально.

**Comment by starline** [comment]
Еще дополню данную тему. Проблему на некоторых машинах можно решить. Установить драйвер с поддержкой SSE2.

**Comment by Peter6891** [comment]
а где его взять? (и драйвер чего? - CH340G ?)
