### ISSUE TITLE
Version 1.1.1

### ISSUE THREAD

**Issue by frobgm** [Denvi/Candle#90]
Hello Denvi
I tried yours new version, 
the presets the older 0.9 version is better than new version 1.1 and 1.1.1 

and windows 1.1.1 version doesn't show opened g-code drawing
linux 1.1.1 version drawing good

and please upload english/english translation file, I like translate hungarian language
thanks!
Robert

**Comment by Denvi** [comment]
Hi, what presets you are talking about?

> upload english/english translation file

Version 1.1 is pre-release, will upload close to release.

**Comment by frobgm** [comment]
![vers111](https://cloud.githubusercontent.com/assets/23508721/20642394/1b6d6f9e-b40e-11e6-89c0-624f060d9609.jpg)
the new 1.1.1 version program jog presets
![vers11](https://cloud.githubusercontent.com/assets/23508721/20642395/1f066746-b40e-11e6-9edb-25b3dfc6c042.jpg)
and the older version 0.9, I think better than ver1.1.1  jog presets

**Comment by Denvi** [comment]
Old version has presets for jog "Step", new one - "Feed".  Last one works with new jog function of Grbl v1.1, where you can continuously move tool in selected direction by holding cursor buttons/keys.
May be you want other feed values?

**Comment by frobgm** [comment]
:( not so good, I used some big cnc machine, all of them machines jog function using predefined distance
0.01 , 0.1, 1, 10, 100 mm 
for example therefore very easy setting the work null point with calibrated steel piece, without electronic  null probe 

it could be two row button? first feed rate, second step distance

**Comment by Denvi** [comment]
Will think about it.

**Comment by frobgm** [comment]
Thanks! I hope :)

**Comment by Denvi** [comment]
Buttons replaced with 2 comboboxes, "Stop"-button added.

Numpad bindings:
- \<\\> - spindle speed decrease;
- \<*\> - spindle speed increase;
- \<7\> - previous step;
- \<1\> - next step;
- \<-\> - previous feed;
- \<+\> - next feed.

[Candle_1.1.3.zip](https://github.com/Denvi/Candle/releases/download/v1.1/Candle_1.1.3.zip)

**Comment by frobgm** [comment]
Hello Denvi
Thanks!

**Comment by frobgm** [comment]
one thing, since version 1.1 on virtulbox windows 7 doesn't show nothing the drawing window , I usualy tested first there...
not big problem, just tell

**Comment by Denvi** [comment]
Have you installed Guest Additions & turned on "3D acceleration" in machine options?

**Comment by frobgm** [comment]
No, so far doesn't need it, the older version working well without "3D acceleration"...
but not big problem, I tested another pc...or linux version :)

**Comment by Denvi** [comment]
There is some features with OpenGL realization among different versions of Qt, thus for 5.4.2 we need 3d acceleration option for virtual box guest.

**Comment by frobgm** [comment]
I understand!
Thank you for your work!

**Comment by frobgm** [comment]
I read some post yours program how to run raspberry pi 3, so I little bit lost, you have a simple method how I run yours program on raspberry?
You try on raspberry? how fast ? ( youtube vid ?)

**Comment by Denvi** [comment]
I haven't run program on Raspberry 3, and think there is no simple method to do it.

**Comment by frobgm** [comment]
Dear Denvi
I try to using ver 1.1.4 new 2 combo boxes , not so good...
feed rate not to important, but to you need it could be slider?
and the distance , the oldiest buttons, one row, four or five buttons?
easier to choose I think...

**Comment by Denvi** [comment]
Buttons works well only with one parameter (feed or speed) not both (to many buttons to select) and it isn't expansible (can't add more presets).
Sliders doesn't show values (user can't see what he selects). Doesn't works well with discrete nonuniform values.
So far I will leave as is, at least until it's a better idea.

**Comment by frobgm** [comment]
I understand and you're right.
and I can't think of a better now...
Perhaps the command state response window it could be smaller, and some button bottom or between two window ( showing and command window)  , just I thinking "loudly" :)
I try the Scroll Lock button, it is great idea!

Which Qt version do you use ?

**Comment by Denvi** [comment]
All recent builds on Qt 5.4.2.
5.5 - problems with deployment on linux platform.
5.7 - only 64-bit version for linux.

**Comment by frobgm** [comment]
Thank you for your answer!

**Comment by frobgm** [comment]
Hello Denvi
I played a bit picture manipulating sw, look this :)
![candle](https://cloud.githubusercontent.com/assets/23508721/20858921/f9c5ba9e-b94f-11e6-84fd-604cf8a07fd6.jpg)

too much sliding on the right side, I think on the bottom place from may be more useful things, and the g-code window there could be a new tab 

I think from usable your program...
What do you think?

**Comment by Denvi** [comment]
Yes, some panels need to be removed from right side. 
So far I adhere to the following idea: file manipulation - left side, cnc control - right side.
Program/console - dock widgets, can be placed on bottom/left/right side of visualizer, including one place with tabs.

![1](https://cloud.githubusercontent.com/assets/5119037/20859294/7719a9ac-b97c-11e6-87b3-dc8065c288d0.png)
![2](https://cloud.githubusercontent.com/assets/5119037/20859297/7ac3a72e-b97c-11e6-8070-0deaac21db22.png)
![3](https://cloud.githubusercontent.com/assets/5119037/20859299/7db34c96-b97c-11e6-8f6d-34b5ed0c823a.png)

But it will be made not soon.

**Comment by frobgm** [comment]
Why important for you the program and the console window?
I think right side  buttons and features important looking all times, and get without slide.
and the screens , usually the screens have 16:9 ratio, now yours program version not to friendly this ratio :)
I think you look for it after...

have nice day!

**Comment by frobgm** [comment]
I thinking all day what is the simple solution.
one idea the right side buttons and features it could be to columns, what do you think?

**Comment by Denvi** [comment]
Anyway i think columns layouts are more flexible than rows, look for "Blender" old versions & latest.

**Comment by frobgm** [comment]
I looked it up, 
see the picture
![trumpf](https://cloud.githubusercontent.com/assets/23508721/20861170/6fc3f312-b989-11e6-935d-601d05ba22f2.jpg)

all buttons have a right side, not both , but if you thinking left-handed people, one tick on the settings page left or right handed.

I think the people like see the drawing window, and doesn't like through out his hand the drawing window
on my opinion one side button heap and bottom, this is handy

 yours program, but I say my opinion :)

**Comment by Denvi** [comment]
All things are good in moderation.

![iss90_1](https://cloud.githubusercontent.com/assets/5119037/20861292/280e45fc-b9ae-11e6-86f6-50c049b0d3e9.jpg)

> I think the people like see the drawing window, and doesn't like through out his hand the drawing window
on my opinion one side button heap and bottom, this is handy

Agree with you, but some things can be placed everywhere.

**Comment by frobgm** [comment]
:)
not to important things really placed everywhere...
but important operation buttons are usually one place
that your  program is it, but opening little windows and scrolling .... this should be changed

**Comment by frobgm** [comment]
Hello Denvi
I found same which like it
http://wiki.linuxcnc.org/uploads/gmoccapy_4_axis.png
I think the layout is good.... what do you think?
but this program layout made 5:4 screen, which is becoming increasingly rare
16:9 screen ratio has all laptops and many desktop computer...but you must know :)

and your program screen colouring is better than me as gmoccapy screen

**Comment by frobgm** [comment]
even an idea guide  :)
http://www.polgardidesign.hu/images/stories/UCCNC.png
over many tabs, on the left the blue streak is the hidden jog buttons...

**Comment by Denvi** [comment]
The user interface will change over time.
