### ISSUE TITLE
Pressing Pause or Abort button causes an unknown status.

### ISSUE THREAD

**Issue by tacitus-def** [Denvi/Candle#92]
Pressing Pause or Abort button causes an unknown status and after this buttons not react a clicking.

Candle version: 1.1.4
OS: Ubuntu 16.04, 64 bit

![_2016-11-29_18-16-56](https://cloud.githubusercontent.com/assets/5925996/20703704/759989d8-b668-11e6-9e54-217d7965ecde.png)

**Comment by Denvi** [comment]
Candle 1.1 is for Grbl 1.1 firmware version.

**Comment by tacitus-def** [comment]
Oops…
