### ISSUE TITLE
simulation

### ISSUE THREAD

**Issue by Peter6891** [Denvi/Candle#93]
and simulation mode processing and rendering the trajectory milling cutters motion only works when the connected circuit board in the machine?
It is impossible to do so and could not connect to the board to check the control code for the machine and view the trajectory of movement of milling cutters?

**Comment by Denvi** [comment]
There is no simulation function and won't be in Candle. Only check through firmware.

**Comment by Peter6891** [comment]
![759989d8-b668-11e6-9e54-217d7965ecde](https://cloud.githubusercontent.com/assets/23585234/20724749/16aa9c72-b678-11e6-9f41-c5dd52d02425.jpg)

**Comment by Peter6891** [comment]
there are red circled "test mode" - this is what test? Is it not a simulation control program ??

**Comment by Denvi** [comment]
No. It is "Check mode" = "$C" - command, described in GRBL firmware docs.
