### ISSUE TITLE
Lagging Sending

### ISSUE THREAD

**Issue by Konesuke** [Denvi/Candle#97]
When i'm sending blocks at feed speed much high, the sender works too slow: the router reach the last position sended than stops waiting new code, then sops, then starts. Like lagging. It is possible to modify tha number of gcode sending at time?

**Comment by Denvi** [comment]
Hi, please:
* $$ - command output
* settings.ini file
* fragment of g-code program

> It is possible to modify tha number of gcode sending at time

Sender already force buffer to be filled during sending.

**Comment by Konesuke** [comment]
Sorry problem solved downloading the software again and reconfigurating all...
